#!/usr/bin/env node
/**
 * snarkjs -> Soroban BN254 artifact converter.
 *
 * Converts our real snarkjs Groth16 verification keys, proofs and public
 * signals into the exact byte layout the on-chain `tessera-ledger`
 * contract's `from_bytes` expects.
 *
 * Byte layout (matches soroban_sdk crypto::bn254 from_bytes and the
 * Nethermind reference contracts/soroban-utils encoders):
 *   Fq/Fr : 32-byte big-endian
 *   G1    : x(32) || y(32)                              = 64 bytes
 *   G2    : x.c1(32) || x.c0(32) || y.c1(32) || y.c0(32) = 128 bytes
 *           (Soroban G2 is imaginary component first, then real)
 *   Proof : A(G1,64) || B(G2,128) || C(G1,64)          = 256 bytes
 *
 * snarkjs JSON conventions:
 *   G1 point = [x_dec, y_dec, "1"]
 *   G2 point = [[x_c0_dec, x_c1_dec], [y_c0_dec, y_c1_dec], ["1","0"]]
 *
 * Outputs:
 *   contracts/tessera-ledger/src/vk_data.rs        (compile-time VK consts)
 *   contracts/tessera-ledger/src/test_fixtures.rs  (real proofs for cargo test)
 *   contracts/artifacts/onchain-args.json          (hex args for stellar CLI)
 */

const fs = require("fs");
const path = require("path");

const PROJECT = path.resolve(__dirname, "../..");
const SRC = path.join(PROJECT, "contracts/tessera-ledger/src");
const ART = path.join(PROJECT, "contracts/artifacts");
fs.mkdirSync(ART, { recursive: true });

// ---- field element encoding -------------------------------------------------

function feBytes(dec) {
  let v = BigInt(dec);
  if (v < 0n) throw new Error("negative field element");
  const out = new Uint8Array(32); // big-endian
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  if (v !== 0n) throw new Error("field element exceeds 32 bytes: " + dec);
  return out;
}

function concat(arrs) {
  const total = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const a of arrs) {
    out.set(a, o);
    o += a.length;
  }
  return out;
}

// snarkjs G1 [x, y, "1"] -> 64 bytes (x || y)
function g1Bytes(pt) {
  return concat([feBytes(pt[0]), feBytes(pt[1])]);
}

// snarkjs G2 [[x_c0, x_c1], [y_c0, y_c1], ...] -> 128 bytes
// Soroban order: x.c1 || x.c0 || y.c1 || y.c0
function g2Bytes(pt) {
  const xc0 = pt[0][0], xc1 = pt[0][1];
  const yc0 = pt[1][0], yc1 = pt[1][1];
  return concat([feBytes(xc1), feBytes(xc0), feBytes(yc1), feBytes(yc0)]);
}

function toHex(bytes) {
  return Buffer.from(bytes).toString("hex");
}

// ---- Rust literal helpers ---------------------------------------------------

function rustArray(bytes) {
  return "[" + Array.from(bytes).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") + "]";
}

function vkToRust(prefix, vk) {
  const alpha = g1Bytes(vk.vk_alpha_1);
  const beta = g2Bytes(vk.vk_beta_2);
  const gamma = g2Bytes(vk.vk_gamma_2);
  const delta = g2Bytes(vk.vk_delta_2);
  const ic = vk.IC.map(g1Bytes);

  let s = "";
  s += `pub const ${prefix}_ALPHA: [u8; 64] = ${rustArray(alpha)};\n`;
  s += `pub const ${prefix}_BETA: [u8; 128] = ${rustArray(beta)};\n`;
  s += `pub const ${prefix}_GAMMA: [u8; 128] = ${rustArray(gamma)};\n`;
  s += `pub const ${prefix}_DELTA: [u8; 128] = ${rustArray(delta)};\n`;
  s += `pub const ${prefix}_IC_LEN: usize = ${ic.length};\n`;
  s += `pub const ${prefix}_IC: [[u8; 64]; ${ic.length}] = [\n`;
  for (const p of ic) s += `    ${rustArray(p)},\n`;
  s += `];\n`;
  return s;
}

function proofBytes(proof) {
  return concat([g1Bytes(proof.pi_a), g2Bytes(proof.pi_b), g1Bytes(proof.pi_c)]);
}

// ---- load inputs ------------------------------------------------------------

const vkSolvency = JSON.parse(fs.readFileSync(path.join(PROJECT, "circuit-keys/vk_solvency.json")));
const vkInclusion = JSON.parse(fs.readFileSync(path.join(PROJECT, "circuit-keys/vk_inclusion.json")));

const proofSolvency = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/solvency_proof.json")));
const pubSolvency = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/solvency_public.json")));
const proofInclusion = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/inclusion_proof.json")));
const pubInclusion = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/inclusion_public.json")));

// ---- vk_data.rs -------------------------------------------------------------

let vkRs = "";
vkRs += "// Auto-generated by contracts/scripts/convert.js from snarkjs vk_*.json.\n";
vkRs += "// Do NOT edit by hand. Byte layout: G1 = x||y, G2 = c1||c0 per component (Soroban).\n\n";
vkRs += vkToRust("VK_SOLVENCY", vkSolvency) + "\n";
vkRs += vkToRust("VK_INCLUSION", vkInclusion);
fs.writeFileSync(path.join(SRC, "vk_data.rs"), vkRs);

// ---- test_fixtures.rs -------------------------------------------------------

const solProof = proofBytes(proofSolvency);
const incProof = proofBytes(proofInclusion);

// Tampered proof: valid on-curve points but wrong assignment.
// Replace A with C (a real G1 point on the curve, wrong role) => pairing fails,
// but every point still decodes cleanly, so the contract reaches the pairing
// check and returns InvalidProof (not a malformed-point panic).
const tamperedSol = concat([
  g1Bytes(proofSolvency.pi_c), // A <- C
  g2Bytes(proofSolvency.pi_b),
  g1Bytes(proofSolvency.pi_c),
]);

function pubToRust(name, pub) {
  let s = `pub const ${name}: [[u8; 32]; ${pub.length}] = [\n`;
  for (const sig of pub) s += `    ${rustArray(feBytes(sig))},\n`;
  s += `];\n`;
  return s;
}

let fx = "";
fx += "// Auto-generated by contracts/scripts/convert.js from our REAL snarkjs proofs.\n";
fx += "// These are the exact bytes submitted on-chain (see contracts/artifacts/onchain-args.json).\n\n";
fx += `pub const SOLVENCY_PROOF: [u8; 256] = ${rustArray(solProof)};\n`;
fx += pubToRust("SOLVENCY_PUBLIC", pubSolvency) + "\n";
fx += `pub const SOLVENCY_PROOF_TAMPERED: [u8; 256] = ${rustArray(tamperedSol)};\n\n`;
fx += `pub const INCLUSION_PROOF: [u8; 256] = ${rustArray(incProof)};\n`;
fx += pubToRust("INCLUSION_PUBLIC", pubInclusion);
fs.writeFileSync(path.join(SRC, "test_fixtures.rs"), fx);

// ---- onchain-args.json (hex for stellar CLI) --------------------------------

const args = {
  note: "Real BN254 Groth16 artifacts encoded for the tessera-ledger Soroban contract.",
  solvency: {
    proof_hex: toHex(solProof),
    public_hex: pubSolvency.map((s) => toHex(feBytes(s))),
    public_dec: pubSolvency,
  },
  solvency_tampered: {
    proof_hex: toHex(tamperedSol),
    public_hex: pubSolvency.map((s) => toHex(feBytes(s))),
  },
  inclusion: {
    proof_hex: toHex(incProof),
    public_hex: pubInclusion.map((s) => toHex(feBytes(s))),
    public_dec: pubInclusion,
  },
};
fs.writeFileSync(path.join(ART, "onchain-args.json"), JSON.stringify(args, null, 2));

console.log("wrote src/vk_data.rs, src/test_fixtures.rs, artifacts/onchain-args.json");
console.log("solvency proof bytes:", solProof.length, "public sigs:", pubSolvency.length);
console.log("inclusion proof bytes:", incProof.length, "public sigs:", pubInclusion.length);
console.log("solvency rootHash == inclusion rootHash:", pubSolvency[0] === pubInclusion[0]);