#!/usr/bin/env node
/**
 * convert_signed.js  --  UPGRADE 1 IN-CIRCUIT EdDSA + FIX 1 on-chain artifact
 * converter.
 *
 * Encodes the rebuilt signed_solvency VK + REAL Groth16 proofs for the Soroban
 * contract. FIX 1 exposes each leaf's signer key as a PUBLIC input, so the
 * public-signal layout is now 12 signals (13 IC):
 *   [ rootHash, totalLiabilities, reserves, epoch, Ax[0..3], Ay[0..3] ]
 *
 * Writes:
 *   contracts/tessera-ledger/src/signed_vk_data.rs          (VK_SIGNED_SOLVENCY)
 *   contracts/tessera-ledger/src/signed_incircuit_fixtures.rs (proofs + keys)
 *   contracts/artifacts/signed-incircuit-args.json             (hex for stellar CLI)
 *
 * Emits the HONEST proof (verifies + stores) and the OMISSION proof (a valid
 * proof whose slot-C public key is the issuer's filler key, so the contract's
 * key pin REJECTS it on-chain). REGISTERED_AX/AY are derived directly from the
 * honest proof's public signals so the on-chain pin and the self-registered list
 * are byte-identical.
 */

const fs = require("fs");
const path = require("path");

const PROJECT = path.resolve(__dirname, "../..");
const SRC = path.join(PROJECT, "contracts/tessera-ledger/src");
const ART = path.join(PROJECT, "contracts/artifacts");
fs.mkdirSync(ART, { recursive: true });

const N_LEAVES = 4;

function feBytes(dec) {
  let v = BigInt(dec);
  if (v < 0n) throw new Error("negative field element");
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
  if (v !== 0n) throw new Error("field element exceeds 32 bytes: " + dec);
  return out;
}
function concat(arrs) {
  const total = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const a of arrs) { out.set(a, o); o += a.length; }
  return out;
}
function g1Bytes(pt) { return concat([feBytes(pt[0]), feBytes(pt[1])]); }
function g2Bytes(pt) {
  const xc0 = pt[0][0], xc1 = pt[0][1], yc0 = pt[1][0], yc1 = pt[1][1];
  return concat([feBytes(xc1), feBytes(xc0), feBytes(yc1), feBytes(yc0)]);
}
function toHex(bytes) { return Buffer.from(bytes).toString("hex"); }
function rustArray(bytes) {
  return "[" + Array.from(bytes).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") + "]";
}
function vkToRust(prefix, vk) {
  const ic = vk.IC.map(g1Bytes);
  let s = "";
  s += `pub const ${prefix}_ALPHA: [u8; 64] = ${rustArray(g1Bytes(vk.vk_alpha_1))};\n`;
  s += `pub const ${prefix}_BETA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_beta_2))};\n`;
  s += `pub const ${prefix}_GAMMA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_gamma_2))};\n`;
  s += `pub const ${prefix}_DELTA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_delta_2))};\n`;
  s += `pub const ${prefix}_IC_LEN: usize = ${ic.length};\n`;
  s += `pub const ${prefix}_IC: [[u8; 64]; ${ic.length}] = [\n`;
  for (const p of ic) s += `    ${rustArray(p)},\n`;
  s += `];\n`;
  return s;
}
function proofBytes(proof) {
  return concat([g1Bytes(proof.pi_a), g2Bytes(proof.pi_b), g1Bytes(proof.pi_c)]);
}
function pubToRust(name, pub) {
  let s = `pub const ${name}: [[u8; 32]; ${pub.length}] = [\n`;
  for (const sig of pub) s += `    ${rustArray(feBytes(sig))},\n`;
  s += `];\n`;
  return s;
}
function keysToRust(name, arr) {
  let s = `pub const ${name}: [[u8; 32]; ${arr.length}] = [\n`;
  for (const v of arr) s += `    ${rustArray(feBytes(v))},\n`;
  s += `];\n`;
  return s;
}

const vk = JSON.parse(fs.readFileSync(path.join(PROJECT, "circuit-keys/vk_signed_solvency.json")));
const proof = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/signed_solvency_proof.json")));
const pub = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/signed_solvency_public.json")));
const omProof = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/signed_solvency_omitted_proof.json")));
const omPub = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/signed_solvency_omitted_public.json")));

if (pub.length !== 4 + 2 * N_LEAVES) throw new Error("unexpected public signal count: " + pub.length);

// Registered keys are exactly the honest proof's public signer keys:
//   Ax[i] = pub[4+i],  Ay[i] = pub[4+N+i].
const regAx = [], regAy = [];
for (let i = 0; i < N_LEAVES; i++) {
  regAx.push(pub[4 + i]);
  regAy.push(pub[4 + N_LEAVES + i]);
}

// ---- signed_vk_data.rs ----
let vkRs = "";
vkRs += "// Auto-generated by contracts/scripts/convert_signed.js from vk_signed_solvency.json.\n";
vkRs += "// UPGRADE 1 IN-CIRCUIT EdDSA + FIX 1 verification key (12 public signals, 13 IC).\n\n";
vkRs += vkToRust("VK_SIGNED_SOLVENCY", vk);
fs.writeFileSync(path.join(SRC, "signed_vk_data.rs"), vkRs);

// ---- signed_incircuit_fixtures.rs ----
const proofB = proofBytes(proof);
const tampered = concat([g1Bytes(proof.pi_c), g2Bytes(proof.pi_b), g1Bytes(proof.pi_c)]);
const omProofB = proofBytes(omProof);

let fx = "";
fx += "// Auto-generated by contracts/scripts/convert_signed.js from the REAL rebuilt\n";
fx += "// in-circuit EdDSA signed_solvency proofs (FIX 1: signer keys are PUBLIC).\n";
fx += "// Public: [rootHash, totalLiabilities, reserves, epoch, Ax[0..3], Ay[0..3]].\n\n";
fx += `pub const SIGNED_SOLVENCY_PROOF: [u8; 256] = ${rustArray(proofB)};\n`;
fx += pubToRust("SIGNED_SOLVENCY_PUBLIC", pub) + "\n";
fx += `pub const SIGNED_SOLVENCY_PROOF_TAMPERED: [u8; 256] = ${rustArray(tampered)};\n\n`;
fx += "/// Ordered registered member Baby-JubJub keys (== honest proof public keys).\n";
fx += "/// Each member self-registers (ax, ay) under their own auth; the contract\n";
fx += "/// pins the proof's public keys against this list, position-by-position.\n";
fx += keysToRust("REGISTERED_AX", regAx);
fx += keysToRust("REGISTERED_AY", regAy) + "\n";
fx += "/// OMISSION attack: a VALID proof over a book where registered member C was\n";
fx += "/// dropped and an issuer-controlled filler key put in slot C. The contract's\n";
fx += "/// on-chain key pin REJECTS it (RegisteredSetMismatch, #10).\n";
fx += `pub const SIGNED_SOLVENCY_OMITTED_PROOF: [u8; 256] = ${rustArray(omProofB)};\n`;
fx += pubToRust("SIGNED_SOLVENCY_OMITTED_PUBLIC", omPub);
fs.writeFileSync(path.join(SRC, "signed_incircuit_fixtures.rs"), fx);

// ---- CLI hex args ----
const args = {
  note: "REAL rebuilt in-circuit EdDSA signed_solvency Groth16 artifacts (FIX 1). Public signer keys are pinned on-chain to the member-self-registered list.",
  public_layout: ["rootHash", "totalLiabilities", "reserves", "epoch", "Ax[0..3]", "Ay[0..3]"],
  signed_solvency: {
    proof_hex: toHex(proofB),
    public_hex: pub.map((s) => toHex(feBytes(s))),
    public_dec: pub,
  },
  registered_keys: regAx.map((ax, i) => ({
    index: i,
    ax_hex: toHex(feBytes(ax)),
    ay_hex: toHex(feBytes(regAy[i])),
    ax_dec: ax,
    ay_dec: regAy[i],
  })),
  omission: {
    proof_hex: toHex(omProofB),
    public_hex: omPub.map((s) => toHex(feBytes(s))),
    public_dec: omPub,
    note: "valid proof, slot-C public key is the issuer filler; contract pin rejects it",
  },
  tampered_proof_hex: toHex(tampered),
};
fs.writeFileSync(path.join(ART, "signed-incircuit-args.json"), JSON.stringify(args, null, 2));

console.log("wrote signed_vk_data.rs, signed_incircuit_fixtures.rs, signed-incircuit-args.json");
console.log("signed proof bytes:", proofB.length, "public sigs:", pub.length, "IC:", vk.IC.length);
console.log("registered keys:", regAx.length, "omitted public sigs:", omPub.length);