#!/usr/bin/env node
/**
 * convert_risk.js  --  UPGRADE 3 risk_solvency on-chain artifact converter.
 *
 * Encodes the risk_solvency VK + REAL Groth16 proof for the Soroban contract,
 * in the same byte layout as contracts/scripts/convert.js. Writes NEW modules so
 * the base convert.js output is untouched:
 *
 *   contracts/tessera-ledger/src/risk_vk_data.rs          (VK_RISK_SOLVENCY)
 *   contracts/tessera-ledger/src/risk_fixtures.rs (proof + public)
 *   contracts/artifacts/risk-args.json             (hex for stellar CLI)
 *
 * Public-signal layout (risk_solvency):
 *   [ rootHash, totalLiabilities, reserves, maxConcBps, minCollBps ]  (5 signals, 6 IC)
 */

const fs = require("fs");
const path = require("path");

const PROJECT = path.resolve(__dirname, "../..");
const SRC = path.join(PROJECT, "contracts/tessera-ledger/src");
const ART = path.join(PROJECT, "contracts/artifacts");
fs.mkdirSync(ART, { recursive: true });

function feBytes(dec) {
  let v = BigInt(dec);
  if (v < 0n) throw new Error("negative field element");
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
  if (v !== 0n) throw new Error("field element exceeds 32 bytes: " + dec);
  return out;
}
function concat(arrs) {
  const total = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const a of arrs) { out.set(a, o); o += a.length; }
  return out;
}
function g1Bytes(pt) { return concat([feBytes(pt[0]), feBytes(pt[1])]); }
function g2Bytes(pt) {
  const xc0 = pt[0][0], xc1 = pt[0][1], yc0 = pt[1][0], yc1 = pt[1][1];
  return concat([feBytes(xc1), feBytes(xc0), feBytes(yc1), feBytes(yc0)]);
}
function toHex(bytes) { return Buffer.from(bytes).toString("hex"); }
function rustArray(bytes) {
  return "[" + Array.from(bytes).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") + "]";
}
function vkToRust(prefix, vk) {
  const ic = vk.IC.map(g1Bytes);
  let s = "";
  s += `pub const ${prefix}_ALPHA: [u8; 64] = ${rustArray(g1Bytes(vk.vk_alpha_1))};\n`;
  s += `pub const ${prefix}_BETA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_beta_2))};\n`;
  s += `pub const ${prefix}_GAMMA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_gamma_2))};\n`;
  s += `pub const ${prefix}_DELTA: [u8; 128] = ${rustArray(g2Bytes(vk.vk_delta_2))};\n`;
  s += `pub const ${prefix}_IC_LEN: usize = ${ic.length};\n`;
  s += `pub const ${prefix}_IC: [[u8; 64]; ${ic.length}] = [\n`;
  for (const p of ic) s += `    ${rustArray(p)},\n`;
  s += `];\n`;
  return s;
}
function proofBytes(proof) {
  return concat([g1Bytes(proof.pi_a), g2Bytes(proof.pi_b), g1Bytes(proof.pi_c)]);
}
function pubToRust(name, pub) {
  let s = `pub const ${name}: [[u8; 32]; ${pub.length}] = [\n`;
  for (const sig of pub) s += `    ${rustArray(feBytes(sig))},\n`;
  s += `];\n`;
  return s;
}

const vk = JSON.parse(fs.readFileSync(path.join(PROJECT, "circuit-keys/vk_risk_solvency.json")));
const proof = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/risk_solvency_proof.json")));
const pub = JSON.parse(fs.readFileSync(path.join(PROJECT, "build/proofs/risk_solvency_public.json")));

// ---- risk_vk_data.rs ----
let vkRs = "";
vkRs += "// Auto-generated by contracts/scripts/convert_risk.js from vk_risk_solvency.json.\n";
vkRs += "// UPGRADE 3 risk_solvency verification key (5 public signals, 6 IC).\n\n";
vkRs += vkToRust("VK_RISK_SOLVENCY", vk);
fs.writeFileSync(path.join(SRC, "risk_vk_data.rs"), vkRs);

// ---- risk_fixtures.rs ----
const proofB = proofBytes(proof);
// Tampered: A <- C (real on-curve point, wrong role) => pairing fails cleanly.
const tampered = concat([g1Bytes(proof.pi_c), g2Bytes(proof.pi_b), g1Bytes(proof.pi_c)]);


let fx = "";
fx += "// Auto-generated by contracts/scripts/convert_risk.js from the REAL in-circuit\n";
fx += "// risk_solvency proof. Public: [rootHash, totalLiabilities, reserves, maxConcBps, minCollBps].\n\n";
fx += `pub const RISK_SOLVENCY_PROOF: [u8; 256] = ${rustArray(proofB)};\n`;
fx += pubToRust("RISK_SOLVENCY_PUBLIC", pub) + "\n";
fx += `pub const RISK_SOLVENCY_PROOF_TAMPERED: [u8; 256] = ${rustArray(tampered)};\n\n`;

fs.writeFileSync(path.join(SRC, "risk_fixtures.rs"), fx);

// ---- CLI hex args ----
const args = {
  note: "REAL risk_solvency Groth16 artifacts for the tessera-ledger Soroban contract.",
  public_layout: ["rootHash", "totalLiabilities", "reserves", "maxConcBps", "minCollBps"],
  risk_solvency: {
    proof_hex: toHex(proofB),
    public_hex: pub.map((s) => toHex(feBytes(s))),
    public_dec: pub,
  },
  tampered_proof_hex: toHex(tampered),
};
fs.writeFileSync(path.join(ART, "risk-args.json"), JSON.stringify(args, null, 2));

console.log("wrote risk_vk_data.rs, risk_fixtures.rs, risk-args.json");
console.log("signed proof bytes:", proofB.length, "public sigs:", pub.length, "IC:", vk.IC.length);
console.log("maxConcBps:", pub[3], "minCollBps:", pub[4]);