#![no_std]

//! Tessera Ledger — Soroban contract.
//!
//! Verifies real BN254 Groth16 proofs ON-CHAIN using Stellar Protocol 25+ host
//! functions, then stores a ledger attestation only if the proof is valid.
//!
//! Public-signal layout (must match `circuits/README.md`):
//!   solvency  : [rootHash, totalLiabilities, reserves]
//!   inclusion : [rootHash, leafCommitment]
//!
//! Verification keys are embedded at compile time (`vk_data.rs`, generated by
//! `contracts/scripts/convert.js` from our snarkjs `vk_*.json`).

extern crate alloc;

mod groth16;

use groth16::{verify, Groth16Proof, VerificationKey};
use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, panic_with_error, symbol_short, token,
    Address, Bytes, BytesN, Env, Vec, crypto::bn254::Bn254Fr,
};

/// Domain separator prefix for the per-member signed-leaf message. Bound into the
/// bytes each member's ed25519 key signs so a signature for this scheme cannot be
/// replayed as a signature for anything else. Exactly 17 bytes.
const LEAF_DOMAIN: [u8; 17] = *b"TESSERA-MEMBER-V1";

// Compile-time verification keys (real BN254 VKs, big-endian byte layout).
#[allow(dead_code)]
mod vk_data {
    include!("vk_data.rs");
}

// Compile-time VK for the IN-CIRCUIT EdDSA signed-solvency circuit (UPGRADE 1 +
// FIX 1). 12 public signals: [rootHash, totalLiabilities, reserves, epoch,
// Ax[0..3], Ay[0..3]] — each leaf's signer key is public and pinned on-chain.
#[allow(dead_code)]
mod signed_vk_data {
    include!("signed_vk_data.rs");
}

// Compile-time VK for the risk-limit circuit (UPGRADE 3). 5 public signals:
// [rootHash, totalLiabilities, reserves, maxConcBps, minCollBps].
#[allow(dead_code)]
mod risk_vk_data {
    include!("risk_vk_data.rs");
}

/// Number of leaves in the fixed-size signed_solvency demo circuit (depth 2).
/// The customer-self-registered key list must hold EXACTLY this many keys, one
/// per leaf, for a signed attestation to be verifiable.
const SIGNED_SOLVENCY_LEAVES: u32 = 4;

/// Number of public signals each circuit exposes.
const SOLVENCY_N_PUBLIC: u32 = 3;
const INCLUSION_N_PUBLIC: u32 = 2;
/// signed_solvency (FIX 1) exposes each leaf's signer key as a PUBLIC input so
/// the contract can pin it against the customer-self-registered list:
///   [rootHash, totalLiabilities, reserves, epoch, Ax[0..3], Ay[0..3]]
/// = 4 scalars + 4 Ax + 4 Ay = 12 public signals.
const SIGNED_SOLVENCY_N_PUBLIC: u32 = 4 + 2 * SIGNED_SOLVENCY_LEAVES;
/// risk_solvency exposes [rootHash, totalLiabilities, reserves, maxConcBps, minCollBps].
const RISK_SOLVENCY_N_PUBLIC: u32 = 5;

/// BN254 scalar field modulus r (big-endian). Every Groth16 public signal must
/// be a canonical field element `< r`; a non-reduced 32-byte value could alias a
/// canonical one through the host's silent mod-reduction (adversarial-audit M3).
/// r = 21888242871839275222246405745257275088548364400416034343698204186575808495617.
const BN254_FR_MODULUS: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xf0, 0x00, 0x00, 0x01,
];

/// A stored solvency attestation. Its mere existence proves the contract
/// verified the Groth16 proof on-chain (submit panics on an invalid proof)
/// AND that the ZK-declared `reserves` was backed by a real on-chain balance
/// held by `reserve_holder` at ledger `bound_ledger`.
#[contracttype]
#[derive(Clone)]
pub struct Attestation {
    /// Merkle-sum root hash (BN254 Fr, 32-byte big-endian).
    pub root_hash: BytesN<32>,
    /// Total liabilities carried in the root (BN254 Fr).
    pub total_liabilities: BytesN<32>,
    /// ZK-declared reserves figure (BN254 Fr). The circuit proves
    /// `total_liabilities <= reserves`; the contract additionally proves
    /// `reserves <= bound_reserves` (the real on-chain balance below).
    pub reserves: BytesN<32>,
    /// The reserve holder whose live token balance backed this attestation.
    pub reserve_holder: Address,
    /// The token contract (SAC) the reserve balance was read from.
    pub reserve_token: Address,
    /// The reserve holder's live on-chain balance, read cross-contract at
    /// submit time. Enforced `>= reserves`, so this is the real, contract-bound
    /// floor of the reserves figure (not a prover-declared number).
    pub bound_reserves: i128,
    /// Ledger sequence at which the on-chain balance was read and bound.
    pub bound_ledger: u32,
    /// Ledger timestamp at which the attestation was verified and stored.
    pub timestamp: u64,
    /// Monotonic attestation epoch (0-based).
    pub epoch: u32,
    /// `true` iff the reserve holder proved CONTROL of the reserve account by
    /// authorizing this very attestation (Soroban `require_auth`, a per-invocation
    /// ed25519 challenge-signature over the contract + args + a fresh nonce). So a
    /// stored attestation means the reserves are not merely held at `reserve_holder`
    /// but signed for by that account's key at this ledger. See UPGRADE 2.
    pub control_proven: bool,
    /// `true` iff this attestation came from `submit_signed_attestation`, i.e. the
    /// Groth16 proof verified EVERY customer's Baby-JubJub EdDSA signature INSIDE
    /// the circuit AND the proof's public signer keys were pinned, position-by-
    /// position, to the CUSTOMER-self-registered on-chain key list (FIX 1). When
    /// true, liabilities-completeness is enforced by the proof plus the on-chain key
    /// pin: the attested root provably contains exactly the registered customers, no
    /// omissions, no fabricated leaves (subject to the single-contributor trusted-
    /// setup caveat). `false` for a plain `submit_attestation`.
    pub non_omission_in_circuit: bool,
}

/// A risk-limited solvency attestation (UPGRADE 3). Its existence proves the
/// contract verified a Groth16 proof that the whole book is solvent AND that it
/// additionally satisfies portfolio-health limits proven IN THE CIRCUIT:
///   * no single LEAF exceeds `max_conc_bps` basis-points of liabilities, and
///   * reserves are at least `min_coll_bps` basis-points of liabilities.
/// Beats a plain R>=L attestation: a leaf-concentrated or thinly-collateralized
/// book is unprovable, so no such attestation can exist.
///
/// HONEST SCOPE (adversarial-audit FIX 3): the concentration cap is PER-LEAF, not
/// per-customer. The risk circuit's leaves are not bound to registered customer
/// keys, so a whale could split its balance across several leaves to stay under
/// the per-leaf cap. Per-CUSTOMER concentration needs the signed-solvency circuit's
/// keyed leaves (FIX 1) folded into the risk circuit; that is NOT-YET (see docs).
#[contracttype]
#[derive(Clone)]
pub struct RiskAttestation {
    pub root_hash: BytesN<32>,
    pub total_liabilities: BytesN<32>,
    pub reserves: BytesN<32>,
    /// Concentration cap the proof satisfies, in basis points (e.g. 4000 = 40%).
    pub max_conc_bps: u32,
    /// Minimum collateralization the proof satisfies, in bps (e.g. 10500 = 105%).
    pub min_coll_bps: u32,
    /// Reserve holder whose live balance backed this attestation.
    pub reserve_holder: Address,
    pub reserve_token: Address,
    /// Live on-chain balance bound at submit time (`>= reserves`).
    pub bound_reserves: i128,
    pub bound_ledger: u32,
    pub timestamp: u64,
    pub epoch: u32,
}

/// The immutable reserve-binding config set at deploy time.
#[contracttype]
#[derive(Clone)]
pub struct ReserveConfig {
    /// Account/contract that must hold the reserve balance.
    pub reserve_holder: Address,
    /// Token contract (SAC) the reserve balance is read from.
    pub reserve_token: Address,
}

/// One leg of a MULTI-ASSET / MULTI-HOLDER reserve (UPGRADE 2). The issuer can
/// back liabilities with balances spread across several accounts and/or tokens.
/// Each leg contributes `balance(holder, token) * scale_num / scale_den` to the
/// aggregate, where the scale is a fixed-point price/units factor per asset
/// (e.g. a stablecoin leg is 1/1; a leg denominated in an asset worth 2 units
/// each is 2/1). Aggregation sums live on-chain balances, so the backing figure
/// is a fact about chain state, not a prover assertion.
#[contracttype]
#[derive(Clone)]
pub struct ReserveLeg {
    pub holder: Address,
    pub token: Address,
    pub scale_num: i128,
    pub scale_den: i128,
}

/// A multi-asset/multi-holder reserve attestation (UPGRADE 2). Its existence
/// proves the contract verified the solvency proof AND that the declared reserves
/// were `<=` the summed, scaled, live balances of every reserve leg, with EVERY
/// leg holder authorizing (control of all reserve accounts).
#[contracttype]
#[derive(Clone)]
pub struct MultiAttestation {
    pub root_hash: BytesN<32>,
    pub total_liabilities: BytesN<32>,
    pub reserves: BytesN<32>,
    /// Summed scaled live balances across all legs at `bound_ledger`.
    pub aggregate_reserves: i128,
    /// Number of reserve legs aggregated.
    pub leg_count: u32,
    pub bound_ledger: u32,
    pub timestamp: u64,
    pub epoch: u32,
}

/// One user-signed liability leaf (UPGRADE 1 — proof-of-liabilities non-omission).
///
/// Each user signs — with their own Stellar ed25519 key — a canonical message
/// binding their balance, a per-epoch nonce and the exact Merkle-sum leaf
/// commitment they expect the issuer to include. The contract re-verifies that
/// ed25519 signature on-chain when the issuer registers the leaf, so the issuer
/// can NEITHER forge a leaf the user never signed NOR silently downgrade a
/// user's balance (the signature covers the balance). Combined with the on-chain
/// registry below, an omitted user holds a self-authenticating claim proving they
/// should have been counted.
#[contracttype]
#[derive(Clone)]
pub struct SignedLeaf {
    /// User's ed25519 public key (a Stellar account key), 32 bytes.
    pub pubkey: BytesN<32>,
    /// Balance the user attests to (must equal the balance inside the leaf).
    pub balance: i128,
    /// Per-epoch anti-replay nonce chosen by the issuer/user.
    pub nonce: u64,
    /// Merkle-sum leaf commitment `Poseidon(acctCommit, balance)` this user's
    /// leaf occupies in the attested tree. The same value a user checks with
    /// `verify_inclusion`.
    pub leaf_commitment: BytesN<32>,
    /// ed25519 signature by `pubkey` over the canonical leaf message, 64 bytes.
    pub sig: BytesN<64>,
}

/// The on-chain registry of user-signed liability leaves for one epoch — the
/// bulletin board that makes omission detectable. Every `leaf_commitment` here
/// carried a valid user ed25519 signature verified on-chain at registration.
#[contracttype]
#[derive(Clone)]
pub struct SignedRegistry {
    /// Attestation epoch this registry pins to.
    pub epoch: u32,
    /// SHA-256 over the concatenated leaf commitments (order as registered): a
    /// compact commitment to the published signed-leaf set.
    pub registry_root: BytesN<32>,
    /// Number of signed leaves registered.
    pub count: u32,
    /// The user-signed leaf commitments the issuer claims to have included.
    pub leaves: Vec<BytesN<32>>,
}

/// One customer-self-registered Baby-JubJub public key (FIX 1). Appended to the
/// on-chain ordered registered-key list by the customer UNDER THEIR OWN
/// `require_auth`, so the issuer can neither author nor alter the set.
#[contracttype]
#[derive(Clone, PartialEq)]
pub struct CustomerKey {
    /// Stellar account that authorized this Baby-JubJub key slot.
    pub customer: Address,
    /// Baby-JubJub public key x, 32-byte big-endian BN254 field element.
    pub ax: BytesN<32>,
    /// Baby-JubJub public key y.
    pub ay: BytesN<32>,
}

#[contracttype]
enum DataKey {
    /// Latest verified attestation.
    Latest,
    /// Next epoch counter.
    Epoch,
    /// Immutable reserve-binding config (holder + token), set in constructor.
    Config,
    /// Latest per-epoch signed-leaf registry (UPGRADE 1, on-chain ed25519).
    Registry,
    /// Ordered list of CUSTOMER-self-registered Baby-JubJub public keys (FIX 1).
    /// Each entry was appended by the customer under their own `require_auth`;
    /// every in-circuit signed-solvency proof is pinned, position-by-position,
    /// against this list so the issuer cannot omit a registered customer.
    RegisteredKeys,
    /// Highest circuit `epoch` accepted by `submit_signed_attestation` (FIX 4).
    /// A new signed attestation must carry a strictly greater epoch, so a stale
    /// proof cannot be replayed to show old (smaller) liabilities.
    SignedEpoch,
    /// Latest risk-limited attestation (UPGRADE 3).
    RiskLatest,
    /// Multi-asset / multi-holder reserve legs (UPGRADE 2).
    ReserveLegs,
    /// Latest multi-asset/multi-holder attestation (UPGRADE 2).
    MultiLatest,
    /// Root hashes already accepted by any attestation path. Prevents replaying
    /// an old proof/root as a fresh attestation when the circuit has no epoch
    /// public input (fast freshness hardening for base/risk/multi).
    SeenRoot(BytesN<32>),
}

/// Contract-level errors.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    /// The submitted solvency proof failed on-chain verification.
    InvalidSolvencyProof = 1,
    /// Wrong number of public signals for the circuit.
    MalformedPublicInputs = 2,
    /// reserves < totalLiabilities (should be impossible given a valid proof).
    Insolvent = 3,
    /// verify_inclusion called before any attestation was stored.
    NoAttestation = 4,
    /// ZK-declared `reserves` exceeds the reserve holder's real on-chain
    /// balance: the reserves figure is not backed. Attestation is rejected.
    ReserveUnbacked = 5,
    /// `reserves` field element does not fit in the i128 balance domain
    /// (top 16 bytes nonzero or would overflow a positive i128).
    ReservesOutOfRange = 6,
    /// Reserve-binding config was never set (contract deployed without a
    /// constructor). Should be impossible for a correctly deployed instance.
    NotConfigured = 7,
    /// A signed leaf carried a `balance` that disagreed with the balance domain
    /// (negative i128), so its signed message could not be canonically rebuilt.
    BadSignedLeaf = 8,
    /// `register_signed_leaves` was called with an empty leaf set.
    EmptyRegistry = 9,
    /// A signed-solvency proof's public signer keys did not match the ordered
    /// customer-self-registered key list, position-by-position: the proof was
    /// built over a DIFFERENT key set (an omission/substitution attempt).
    /// Rejected on-chain (FIX 1).
    RegisteredSetMismatch = 10,
    /// `submit_signed_attestation` was called before the full customer key list
    /// was self-registered (wrong count of registered keys).
    RegisteredSetNotSet = 11,
    /// Multi-asset reserve legs were never configured (UPGRADE 2).
    NoReserveLegs = 12,
    /// A reserve leg carried a non-1:1 scale (FIX 2: same-unit aggregation only)
    /// or a non-positive scale component.
    BadReserveLeg = 13,
    /// A signed attestation's circuit `epoch` was not strictly greater than the
    /// last accepted signed epoch: a stale/replayed proof (FIX 4).
    StaleEpoch = 14,
    /// Aggregating multi-asset reserve legs overflowed i128 (FIX 5: explicit,
    /// never a silent saturating fallback).
    ReserveOverflow = 15,
    /// A root hash was already accepted by any attestation path. Prevents stale
    /// base/risk/multi proofs from being replayed as fresh Latest roots.
    RootAlreadyAttested = 17,
    /// The fixed signed-solvency demo circuit has exactly four leaf slots; a
    /// fifth registration would brick future signed attestations.
    RegisteredSetFull = 18,
    /// The same Stellar customer tried to register a second Baby-JubJub key.
    CustomerAlreadyRegistered = 19,
    /// A base/risk/multi attestation attempted to overwrite a stronger signed
    /// non-omission Latest root.
    WeakAttestationDowngrade = 20,
    /// Risk proof public policy parameters are weaker than contract policy.
    RiskPolicyTooWeak = 21,
    /// A reserve leg used a different token than the constructor-bound reserve token.
    BadReserveToken = 22,
    /// A Groth16 public signal was not a canonical BN254 field element (`>= r`),
    /// so it could alias a canonical value via silent mod-reduction (FIX 5 / M3).
    NonCanonicalSignal = 16,
}

fn map_g16(e: groth16::Groth16Error) -> Error {
    match e {
        groth16::Groth16Error::InvalidProof => Error::InvalidSolvencyProof,
        groth16::Groth16Error::MalformedPublicInputs => Error::MalformedPublicInputs,
    }
}

/// Convert `Vec<BytesN<32>>` public signals into BN254 field elements.
fn to_fr_vec(env: &Env, signals: &Vec<BytesN<32>>) -> Vec<Bn254Fr> {
    let mut out: Vec<Bn254Fr> = Vec::new(env);
    for s in signals.iter() {
        out.push_back(Bn254Fr::from_bytes(s));
    }
    out
}

fn solvency_vk(env: &Env) -> VerificationKey {
    VerificationKey::from_const(
        env,
        &vk_data::VK_SOLVENCY_ALPHA,
        &vk_data::VK_SOLVENCY_BETA,
        &vk_data::VK_SOLVENCY_GAMMA,
        &vk_data::VK_SOLVENCY_DELTA,
        &vk_data::VK_SOLVENCY_IC,
    )
}

fn inclusion_vk(env: &Env) -> VerificationKey {
    VerificationKey::from_const(
        env,
        &vk_data::VK_INCLUSION_ALPHA,
        &vk_data::VK_INCLUSION_BETA,
        &vk_data::VK_INCLUSION_GAMMA,
        &vk_data::VK_INCLUSION_DELTA,
        &vk_data::VK_INCLUSION_IC,
    )
}

fn signed_solvency_vk(env: &Env) -> VerificationKey {
    VerificationKey::from_const(
        env,
        &signed_vk_data::VK_SIGNED_SOLVENCY_ALPHA,
        &signed_vk_data::VK_SIGNED_SOLVENCY_BETA,
        &signed_vk_data::VK_SIGNED_SOLVENCY_GAMMA,
        &signed_vk_data::VK_SIGNED_SOLVENCY_DELTA,
        &signed_vk_data::VK_SIGNED_SOLVENCY_IC,
    )
}

fn risk_solvency_vk(env: &Env) -> VerificationKey {
    VerificationKey::from_const(
        env,
        &risk_vk_data::VK_RISK_SOLVENCY_ALPHA,
        &risk_vk_data::VK_RISK_SOLVENCY_BETA,
        &risk_vk_data::VK_RISK_SOLVENCY_GAMMA,
        &risk_vk_data::VK_RISK_SOLVENCY_DELTA,
        &risk_vk_data::VK_RISK_SOLVENCY_IC,
    )
}

/// Read a small non-negative BN254 Fr (basis-point value) as a u32. Returns 0 if
/// the value does not fit u32 (a legitimate bps figure is < 2^16).
fn be32_to_u32(b: &BytesN<32>) -> u32 {
    let a = b.to_array();
    ((a[28] as u32) << 24) | ((a[29] as u32) << 16) | ((a[30] as u32) << 8) | (a[31] as u32)
}

/// Interpret a 32-byte big-endian BN254 field element as a non-negative i128
/// (the domain of a Soroban token balance). Returns `None` if the value cannot
/// fit a positive i128 (any of the top 16 bytes set, or the high bit of the
/// low 16 bytes set). Reserve figures are small integers, so a legitimate
/// solvency public input always fits.
fn be32_to_i128(b: &BytesN<32>) -> Option<i128> {
    let a = b.to_array();
    let mut i = 0;
    while i < 16 {
        if a[i] != 0 {
            return None;
        }
        i += 1;
    }
    if a[16] & 0x80 != 0 {
        return None;
    }
    let mut v: i128 = 0;
    let mut j = 16;
    while j < 32 {
        v = (v << 8) | (a[j] as i128);
        j += 1;
    }
    Some(v)
}

/// Unsigned big-endian comparison: returns true if `a >= b`.
fn ge_be(a: &BytesN<32>, b: &BytesN<32>) -> bool {
    let a = a.to_array();
    let b = b.to_array();
    for i in 0..32 {
        if a[i] != b[i] {
            return a[i] > b[i];
        }
    }
    true
}

/// True iff `b` is a canonical BN254 scalar-field element (`b < r`). A public
/// signal that is `>= r` is NOT canonical: the host silently reduces it mod r
/// during `g1_mul`, so a non-canonical encoding could alias a canonical value.
/// Rejecting non-canonical signals closes that aliasing (M3).
fn is_canonical_fr(b: &BytesN<32>) -> bool {
    let modulus = BytesN::from_array(b.env(), &BN254_FR_MODULUS);
    !ge_be(b, &modulus)
}

/// Panic `MalformedPublicInputs` if any public signal is not a canonical field
/// element (`>= r`). Called at the top of every proof-consuming entrypoint,
/// before the field elements reach `g1_mul`.
fn assert_canonical_signals(env: &Env, signals: &Vec<BytesN<32>>) {
    for s in signals.iter() {
        if !is_canonical_fr(&s) {
            panic_with_error!(env, Error::NonCanonicalSignal);
        }
    }
}

#[contract]
pub struct TesseraLedger;

#[contractimpl]
impl TesseraLedger {
    /// Bind this instance to a real on-chain reserve holder and token (SAC).
    /// The reserve figure carried in every future solvency proof is checked
    /// against `reserve_holder`'s live balance in `reserve_token`. Immutable:
    /// there is no setter, so the binding target cannot be rigged post-deploy.
    pub fn __constructor(env: Env, reserve_holder: Address, reserve_token: Address) {
        env.storage().instance().set(
            &DataKey::Config,
            &ReserveConfig {
                reserve_holder,
                reserve_token,
            },
        );
    }

    /// Verify a solvency Groth16 proof on-chain and bind its reserves figure to
    /// a real on-chain balance. Stores the attestation ONLY if all hold:
    ///   1. the Groth16 solvency proof verifies (BN254 pairing check),
    ///   2. `reserves >= totalLiabilities` (defense in depth vs. the circuit),
    ///   3. `reserves <= reserve_holder.balance(reserve_token)` read live,
    ///      cross-contract, at this ledger.
    ///
    /// End-to-end this enforces `totalLiabilities <= reserves <= on-chain
    /// balance`: liabilities are ZK-proven <= reserves, and reserves is
    /// contract-bound to a real token balance the prover cannot fake.
    ///
    /// Panics (nothing is stored) on any failing check. Returns the epoch.
    ///
    /// `public_signals` = [rootHash, totalLiabilities, reserves].
    pub fn submit_attestation(
        env: Env,
        proof: BytesN<256>,
        public_signals: Vec<BytesN<32>>,
    ) -> u32 {
        if public_signals.len() != SOLVENCY_N_PUBLIC {
            panic_with_error!(&env, Error::MalformedPublicInputs);
        }
        assert_canonical_signals(&env, &public_signals);

        let vk = solvency_vk(&env);
        let parsed = Groth16Proof::from_bytes(&env, &proof);
        let fr = to_fr_vec(&env, &public_signals);

        // On-chain BN254 Groth16 verification. Panics on failure => no storage.
        if let Err(e) = verify(&env, &vk, &parsed, &fr) {
            panic_with_error!(&env, map_g16(e));
        }

        let root_hash = public_signals.get_unchecked(0);
        let total_liabilities = public_signals.get_unchecked(1);
        let reserves = public_signals.get_unchecked(2);

        reject_seen_root(&env, &root_hash);
        reject_weak_downgrade(&env);

        // Defense in depth: the circuit already enforces total <= reserves, but
        // reject on-chain too so a stored attestation always means "solvent".
        if !ge_be(&reserves, &total_liabilities) {
            panic_with_error!(&env, Error::Insolvent);
        }

        // ---- Reserve binding: the differentiator ----
        // Read the reserve holder's LIVE token balance cross-contract and
        // require the ZK-declared reserves to be backed by it. This makes the
        // reserves figure a fact about chain state, not a prover assertion.
        let config: ReserveConfig = match env.storage().instance().get(&DataKey::Config) {
            Some(c) => c,
            None => panic_with_error!(&env, Error::NotConfigured),
        };

        // ---- UPGRADE 2: proof of ASSETS CONTROL ----
        // Require the reserve holder to AUTHORIZE this attestation. Soroban
        // `require_auth` forces a per-invocation ed25519 challenge-signature by
        // the reserve holder's key over (this contract, "submit_attestation",
        // these args) plus a fresh replay-proof nonce. So the bound reserve is a
        // CONTROLLED account, not merely an address that happens to hold tokens:
        // an issuer who does not control `reserve_holder` cannot produce this
        // authorization and the attestation cannot be stored.
        config.reserve_holder.require_auth();

        let declared_reserves = match be32_to_i128(&reserves) {
            Some(v) => v,
            None => panic_with_error!(&env, Error::ReservesOutOfRange),
        };

        let onchain_reserves =
            token::TokenClient::new(&env, &config.reserve_token).balance(&config.reserve_holder);

        if declared_reserves > onchain_reserves {
            // The prover declared more reserves than actually exist on-chain.
            panic_with_error!(&env, Error::ReserveUnbacked);
        }

        let bound_ledger = env.ledger().sequence();

        let store = env.storage().persistent();
        let epoch: u32 = store.get(&DataKey::Epoch).unwrap_or(0);

        let attestation = Attestation {
            root_hash: root_hash.clone(),
            total_liabilities,
            reserves,
            reserve_holder: config.reserve_holder.clone(),
            reserve_token: config.reserve_token.clone(),
            bound_reserves: onchain_reserves,
            bound_ledger,
            timestamp: env.ledger().timestamp(),
            epoch,
            control_proven: true,
            non_omission_in_circuit: false,
        };

        store.set(&DataKey::Latest, &attestation);
        mark_root_seen(&env, &root_hash);
        store.set(&DataKey::Epoch, &(epoch + 1));

        env.events().publish(
            (symbol_short!("ledger"), symbol_short!("attested")),
            (epoch, root_hash, onchain_reserves),
        );

        epoch
    }

    /// Verify a user's inclusion Groth16 proof on-chain against the currently
    /// stored solvent rootHash.
    ///
    /// Returns `true` only if (a) an attestation exists, (b) the proof's
    /// rootHash equals the stored rootHash, and (c) the inclusion proof verifies
    /// on-chain. Returns `false` on a root mismatch or an invalid proof.
    ///
    /// `public_signals` = [rootHash, leafCommitment].
    pub fn verify_inclusion(
        env: Env,
        proof: BytesN<256>,
        public_signals: Vec<BytesN<32>>,
    ) -> bool {
        if public_signals.len() != INCLUSION_N_PUBLIC {
            panic_with_error!(&env, Error::MalformedPublicInputs);
        }
        assert_canonical_signals(&env, &public_signals);

        let store = env.storage().persistent();
        let latest: Attestation = match store.get(&DataKey::Latest) {
            Some(a) => a,
            None => panic_with_error!(&env, Error::NoAttestation),
        };

        // The inclusion proof must reference the certified-solvent root.
        let claimed_root = public_signals.get_unchecked(0);
        if claimed_root != latest.root_hash {
            return false;
        }

        let vk = inclusion_vk(&env);
        let parsed = Groth16Proof::from_bytes(&env, &proof);
        let fr = to_fr_vec(&env, &public_signals);

        matches!(verify(&env, &vk, &parsed, &fr), Ok(true))
    }

    /// Return the latest verified attestation, if any.
    pub fn get_attestation(env: Env) -> Option<Attestation> {
        env.storage().persistent().get(&DataKey::Latest)
    }

    /// Number of attestations stored so far (next epoch index).
    pub fn epoch_count(env: Env) -> u32 {
        env.storage().persistent().get(&DataKey::Epoch).unwrap_or(0)
    }

    /// The immutable reserve-binding config (holder + token) this instance was
    /// deployed against.
    pub fn reserve_config(env: Env) -> Option<ReserveConfig> {
        env.storage().instance().get(&DataKey::Config)
    }

    /// The reserve holder's LIVE balance in the bound token, read right now,
    /// cross-contract. Lets the public board show current backing independent
    /// of the last attestation. Panics `NotConfigured` if never configured.
    pub fn live_reserve_balance(env: Env) -> i128 {
        let config: ReserveConfig = match env.storage().instance().get(&DataKey::Config) {
            Some(c) => c,
            None => panic_with_error!(&env, Error::NotConfigured),
        };
        token::TokenClient::new(&env, &config.reserve_token).balance(&config.reserve_holder)
    }

    /// Compact binding info from the latest attestation:
    /// `(reserve_holder, bound_reserves, bound_ledger)`.
    pub fn bound_reserve_info(env: Env) -> Option<(Address, i128, u32)> {
        env.storage()
            .persistent()
            .get::<_, Attestation>(&DataKey::Latest)
            .map(|a| (a.reserve_holder, a.bound_reserves, a.bound_ledger))
    }

    // ===== UPGRADE 1: proof-of-liabilities NON-OMISSION =====

    /// Register the set of user-signed liability leaves for the current
    /// attestation epoch — the on-chain bulletin board that makes account
    /// omission detectable.
    ///
    /// For every leaf the contract rebuilds the exact canonical message the user
    /// signed and verifies its ed25519 signature ON-CHAIN (`ed25519_verify`,
    /// which panics on any invalid signature). Therefore the stored registry can
    /// only ever contain leaves that were genuinely signed by their owner's key
    /// for THIS epoch and THIS balance: the issuer cannot fabricate a leaf for a
    /// user it doesn't have a signature from, nor downgrade a user's balance
    /// (the signature commits to the balance and the exact leaf commitment).
    ///
    /// A user later confirms two things: (a) their leaf is `is_registered`, and
    /// (b) `verify_inclusion` passes against the attested Merkle-sum root. If the
    /// issuer omitted them, at least one fails while `verify_signed_claim` still
    /// proves — on-chain — that they DID authorize a balance this epoch. That is
    /// the omission proof (subject to the user actually checking; see docs).
    ///
    /// Returns the number of signed leaves registered. Panics if the set is
    /// empty, no attestation exists yet, or any signature is invalid.
    pub fn register_signed_leaves(env: Env, leaves: Vec<SignedLeaf>) -> u32 {
        if leaves.is_empty() {
            panic_with_error!(&env, Error::EmptyRegistry);
        }

        // Pin the registry to the epoch of the currently attested root.
        let latest: Attestation = match env.storage().persistent().get(&DataKey::Latest) {
            Some(a) => a,
            None => panic_with_error!(&env, Error::NoAttestation),
        };
        let epoch = latest.epoch;

        let mut commitments: Vec<BytesN<32>> = Vec::new(&env);
        let mut concat = Bytes::new(&env);
        for leaf in leaves.iter() {
            if leaf.balance < 0 {
                panic_with_error!(&env, Error::BadSignedLeaf);
            }
            let msg = leaf_message(&env, epoch, &leaf);
            // On-chain ed25519 verification: panics (reverts the whole call) on
            // any invalid signature. The issuer cannot register an unsigned or
            // tampered leaf.
            env.crypto().ed25519_verify(&leaf.pubkey, &msg, &leaf.sig);
            commitments.push_back(leaf.leaf_commitment.clone());
            concat.extend_from_array(&leaf.leaf_commitment.to_array());
        }

        let registry_root = env.crypto().sha256(&concat).to_bytes();
        let count = commitments.len();
        let registry = SignedRegistry {
            epoch,
            registry_root: registry_root.clone(),
            count,
            leaves: commitments,
        };
        env.storage().persistent().set(&DataKey::Registry, &registry);

        env.events().publish(
            (symbol_short!("members"), symbol_short!("enrolled")),
            (epoch, registry_root, count),
        );
        count
    }

    /// The latest signed-leaf registry (epoch, SHA-256 registry root, count,
    /// leaf commitments), if any.
    pub fn signed_leaf_registry(env: Env) -> Option<SignedRegistry> {
        env.storage().persistent().get(&DataKey::Registry)
    }

    /// Is `leaf_commitment` present in the current signed-leaf registry? A user
    /// computes their own commitment `Poseidon(acctCommit, balance)` off-chain
    /// and calls this; `false` means the issuer did not even list them (registry
    /// omission).
    pub fn is_registered(env: Env, leaf_commitment: BytesN<32>) -> bool {
        match env
            .storage()
            .persistent()
            .get::<_, SignedRegistry>(&DataKey::Registry)
        {
            Some(r) => {
                for c in r.leaves.iter() {
                    if c == leaf_commitment {
                        return true;
                    }
                }
                false
            }
            None => false,
        }
    }

    /// Re-verify a single user's signed liability claim ON-CHAIN without storing
    /// anything. Panics if the ed25519 signature is invalid; on success returns
    /// the `leaf_commitment` the signature is cryptographically bound to.
    ///
    /// This is the self-authenticating half of an omission proof: an omitted
    /// user (or anyone) calls this to show the chain that the user genuinely
    /// signed `balance` for `epoch` and expected `leaf_commitment` — which can
    /// then be shown absent from `is_registered` / the attested root.
    pub fn verify_signed_claim(env: Env, epoch: u32, leaf: SignedLeaf) -> BytesN<32> {
        if leaf.balance < 0 {
            panic_with_error!(&env, Error::BadSignedLeaf);
        }
        let msg = leaf_message(&env, epoch, &leaf);
        env.crypto().ed25519_verify(&leaf.pubkey, &msg, &leaf.sig);
        leaf.leaf_commitment
    }

    // ===== UPGRADE 1 (STRONGEST FORM): IN-CIRCUIT EdDSA non-omission =====
    // ===== FIX 1: customer-verifiable, issuer-uncontrollable registered set ===

    /// A customer SELF-REGISTERS their Baby-JubJub public key into the on-chain
    /// ordered key list, under THEIR OWN authorization (`customer.require_auth()`).
    ///
    /// This closes the non-omission circularity: previously the ISSUER published a
    /// single `pubkeyHash` under its own auth, so it could commit to `Poseidon(keys
    /// of the subset it wanted)` and prove solvency over that subset, silently
    /// omitting a customer. Now the issuer never authors the set. Each customer
    /// appends their own key, and every `submit_signed_attestation` proof is pinned
    /// position-by-position against this list: an attestation whose signer keys are
    /// not exactly the registered keys is rejected on-chain.
    ///
    /// Idempotent: re-registering an already-present key is a no-op. Returns the
    /// current registered-key count. The `customer` address is the authorizing
    /// party (a customer's Stellar account); `(ax, ay)` is the customer's
    /// Baby-JubJub key used to sign their liability leaf in the circuit.
    pub fn register_customer_key(
        env: Env,
        customer: Address,
        ax: BytesN<32>,
        ay: BytesN<32>,
    ) -> u32 {
        // The customer must authorize inclusion of their OWN key. No issuer path.
        customer.require_auth();

        if !is_canonical_fr(&ax) || !is_canonical_fr(&ay) {
            panic_with_error!(&env, Error::NonCanonicalSignal);
        }

        let store = env.storage().persistent();
        let mut keys: Vec<CustomerKey> = store.get(&DataKey::RegisteredKeys).unwrap_or(Vec::new(&env));

        // Idempotent: skip if this exact key is already registered. A customer
        // may not register a second distinct key, and the fixed depth-2 circuit
        // has exactly four slots, so a fifth registration is rejected instead of
        // bricking future signed attestations.
        for k in keys.iter() {
            if k.ax == ax && k.ay == ay {
                return keys.len();
            }
            if k.customer == customer {
                panic_with_error!(&env, Error::CustomerAlreadyRegistered);
            }
        }
        if keys.len() >= SIGNED_SOLVENCY_LEAVES {
            panic_with_error!(&env, Error::RegisteredSetFull);
        }

        keys.push_back(CustomerKey { customer: customer.clone(), ax: ax.clone(), ay: ay.clone() });
        store.set(&DataKey::RegisteredKeys, &keys);

        let count = keys.len();
        env.events().publish(
            (symbol_short!("member"), symbol_short!("key_add")),
            (customer, ax, ay, count),
        );
        count
    }

    /// Is `(ax, ay)` present in the on-chain customer-self-registered key list?
    /// Any customer calls this to confirm their key was registered (FIX 1
    /// customer-verifiability) without trusting the issuer.
    pub fn is_registered_key(env: Env, ax: BytesN<32>, ay: BytesN<32>) -> bool {
        match env
            .storage()
            .persistent()
            .get::<_, Vec<CustomerKey>>(&DataKey::RegisteredKeys)
        {
            Some(keys) => {
                for k in keys.iter() {
                    if k.ax == ax && k.ay == ay {
                        return true;
                    }
                }
                false
            }
            None => false,
        }
    }

    /// Number of customer keys self-registered so far.
    pub fn registered_key_count(env: Env) -> u32 {
        env.storage()
            .persistent()
            .get::<_, Vec<CustomerKey>>(&DataKey::RegisteredKeys)
            .map(|k| k.len())
            .unwrap_or(0)
    }

    /// The full ordered customer-self-registered key list, if any.
    pub fn registered_keys(env: Env) -> Option<Vec<CustomerKey>> {
        env.storage().persistent().get(&DataKey::RegisteredKeys)
    }

    /// The highest circuit `epoch` accepted by `submit_signed_attestation` so
    /// far, if any (FIX 4 freshness counter). A new signed attestation must carry
    /// a strictly greater epoch.
    pub fn signed_epoch(env: Env) -> Option<u32> {
        env.storage().persistent().get(&DataKey::SignedEpoch)
    }

    /// Verify an IN-CIRCUIT EdDSA signed-solvency Groth16 proof on-chain and store
    /// the attestation only if all hold:
    ///   1. the Groth16 proof verifies (BN254 pairing check) — because the circuit
    ///      checks it, a passing proof means EVERY leaf in the attested tree carries
    ///      a valid Baby-JubJub EdDSA signature by the key exposed for that leaf;
    ///   2. the proof's PUBLIC signer keys `(Ax_i, Ay_i)` equal the customer-self-
    ///      registered ordered key list, position-by-position — so the tree is built
    ///      over EXACTLY the registered customers. The issuer authored none of these
    ///      keys, so it cannot drop a registered customer or add an unregistered one
    ///      (FIX 1: closes the non-omission circularity);
    ///   3. the circuit `epoch` is strictly greater than the last accepted signed
    ///      epoch — a stale proof cannot be replayed (FIX 4 freshness);
    ///   4. `reserves >= totalLiabilities` (defense in depth);
    ///   5. the reserve holder authorizes the attestation (`require_auth`, UPGRADE 2);
    ///   6. `reserves <= reserve_holder.balance(reserve_token)` read live.
    ///
    /// The stored attestation has `non_omission_in_circuit = true`: liabilities
    /// completeness is enforced cryptographically by the proof plus the on-chain
    /// key pin, not by user vigilance. Panics (nothing stored) on any failing
    /// check. Returns the epoch.
    ///
    /// `public_signals` = [rootHash, totalLiabilities, reserves, epoch, Ax[0..3], Ay[0..3]].
    pub fn submit_signed_attestation(
        env: Env,
        proof: BytesN<256>,
        public_signals: Vec<BytesN<32>>,
    ) -> u32 {
        if public_signals.len() != SIGNED_SOLVENCY_N_PUBLIC {
            panic_with_error!(&env, Error::MalformedPublicInputs);
        }
        assert_canonical_signals(&env, &public_signals);

        let vk = signed_solvency_vk(&env);
        let parsed = Groth16Proof::from_bytes(&env, &proof);
        let fr = to_fr_vec(&env, &public_signals);

        // On-chain BN254 Groth16 verification. A passing pairing check means every
        // leaf was signed in-circuit by the PUBLIC key exposed for that leaf.
        if let Err(e) = verify(&env, &vk, &parsed, &fr) {
            panic_with_error!(&env, map_g16(e));
        }

        let root_hash = public_signals.get_unchecked(0);
        let total_liabilities = public_signals.get_unchecked(1);
        let reserves = public_signals.get_unchecked(2);
        let circuit_epoch = public_signals.get_unchecked(3);
        // Public layout: Ax[i] = signal 4+i, Ay[i] = signal 4+N+i.

        reject_seen_root(&env, &root_hash);

        // NON-OMISSION PIN (FIX 1): the proof's public signer keys must equal the
        // customer-self-registered ordered key list, position-by-position. The
        // list must be fully registered (one key per leaf).
        let registered: Vec<CustomerKey> = match env
            .storage()
            .persistent()
            .get(&DataKey::RegisteredKeys)
        {
            Some(k) => k,
            None => panic_with_error!(&env, Error::RegisteredSetNotSet),
        };
        if registered.len() != SIGNED_SOLVENCY_LEAVES {
            panic_with_error!(&env, Error::RegisteredSetNotSet);
        }
        for i in 0..SIGNED_SOLVENCY_LEAVES {
            let ax = public_signals.get_unchecked(4 + i);
            let ay = public_signals.get_unchecked(4 + SIGNED_SOLVENCY_LEAVES + i);
            let k = registered.get_unchecked(i);
            if ax != k.ax || ay != k.ay {
                panic_with_error!(&env, Error::RegisteredSetMismatch);
            }
        }

        // FRESHNESS (FIX 4): require a strictly increasing circuit epoch so a
        // stale proof cannot be replayed to re-show old (smaller) liabilities.
        let new_epoch = match be32_to_i128(&circuit_epoch) {
            Some(v) => v,
            None => panic_with_error!(&env, Error::MalformedPublicInputs),
        };
        if let Some(last) = env
            .storage()
            .persistent()
            .get::<_, u32>(&DataKey::SignedEpoch)
        {
            if new_epoch <= (last as i128) {
                panic_with_error!(&env, Error::StaleEpoch);
            }
        }

        if !ge_be(&reserves, &total_liabilities) {
            panic_with_error!(&env, Error::Insolvent);
        }

        let config: ReserveConfig = match env.storage().instance().get(&DataKey::Config) {
            Some(c) => c,
            None => panic_with_error!(&env, Error::NotConfigured),
        };

        // UPGRADE 2: proof of ASSETS CONTROL.
        config.reserve_holder.require_auth();

        let declared_reserves = match be32_to_i128(&reserves) {
            Some(v) => v,
            None => panic_with_error!(&env, Error::ReservesOutOfRange),
        };

        let onchain_reserves =
            token::TokenClient::new(&env, &config.reserve_token).balance(&config.reserve_holder);

        if declared_reserves > onchain_reserves {
            panic_with_error!(&env, Error::ReserveUnbacked);
        }

        let bound_ledger = env.ledger().sequence();
        let store = env.storage().persistent();
        let epoch: u32 = store.get(&DataKey::Epoch).unwrap_or(0);

        let attestation = Attestation {
            root_hash: root_hash.clone(),
            total_liabilities,
            reserves,
            reserve_holder: config.reserve_holder.clone(),
            reserve_token: config.reserve_token.clone(),
            bound_reserves: onchain_reserves,
            bound_ledger,
            timestamp: env.ledger().timestamp(),
            epoch,
            control_proven: true,
            non_omission_in_circuit: true,
        };

        store.set(&DataKey::Latest, &attestation);
        mark_root_seen(&env, &root_hash);
        store.set(&DataKey::Epoch, &(epoch + 1));
        // Advance the freshness counter (FIX 4): future signed attestations must
        // carry a strictly greater circuit epoch.
        store.set(&DataKey::SignedEpoch, &(new_epoch as u32));

        env.events().publish(
            (symbol_short!("ledger"), symbol_short!("signed")),
            (epoch, root_hash, new_epoch, onchain_reserves),
        );

        epoch
    }

    // ===== UPGRADE 3: CONCENTRATION / RISK LIMITS =====

    /// Verify a risk-limit solvency Groth16 proof on-chain and store a
    /// `RiskAttestation`. Beyond `totalLiabilities <= reserves`, a passing proof
    /// certifies IN ZERO KNOWLEDGE that the book is portfolio-healthy:
    ///   * CONCENTRATION: no single LEAF exceeds `maxConcBps` bps of the book
    ///     (PER-LEAF, not per-customer — see FIX 3 honest scope on `RiskAttestation`),
    ///   * COLLATERALIZATION: reserves are >= `minCollBps` bps of liabilities.
    /// A leaf-concentrated or thinly-collateralized book cannot produce a proof, so
    /// no such attestation can be stored. Reserves are still bound to the real
    /// on-chain balance and the reserve holder still authorizes (UPGRADE 2).
    ///
    /// `public_signals` = [rootHash, totalLiabilities, reserves, maxConcBps, minCollBps].
    pub fn submit_risk_attestation(
        env: Env,
        proof: BytesN<256>,
        public_signals: Vec<BytesN<32>>,
    ) -> u32 {
        if public_signals.len() != RISK_SOLVENCY_N_PUBLIC {
            panic_with_error!(&env, Error::MalformedPublicInputs);
        }
        assert_canonical_signals(&env, &public_signals);

        let vk = risk_solvency_vk(&env);
        let parsed = Groth16Proof::from_bytes(&env, &proof);
        let fr = to_fr_vec(&env, &public_signals);
        if let Err(e) = verify(&env, &vk, &parsed, &fr) {
            panic_with_error!(&env, map_g16(e));
        }

        let root_hash = public_signals.get_unchecked(0);
        let total_liabilities = public_signals.get_unchecked(1);
        let reserves = public_signals.get_unchecked(2);
        let max_conc_bps = be32_to_u32(&public_signals.get_unchecked(3));
        let min_coll_bps = be32_to_u32(&public_signals.get_unchecked(4));

        reject_seen_root(&env, &root_hash);
        reject_weak_downgrade(&env);
        if max_conc_bps > 4000 || min_coll_bps < 10500 {
            panic_with_error!(&env, Error::RiskPolicyTooWeak);
        }

        if !ge_be(&reserves, &total_liabilities) {
            panic_with_error!(&env, Error::Insolvent);
        }

        let config: ReserveConfig = match env.storage().instance().get(&DataKey::Config) {
            Some(c) => c,
            None => panic_with_error!(&env, Error::NotConfigured),
        };
        config.reserve_holder.require_auth();

        let declared_reserves = match be32_to_i128(&reserves) {
            Some(v) => v,
            None => panic_with_error!(&env, Error::ReservesOutOfRange),
        };
        let onchain_reserves =
            token::TokenClient::new(&env, &config.reserve_token).balance(&config.reserve_holder);
        if declared_reserves > onchain_reserves {
            panic_with_error!(&env, Error::ReserveUnbacked);
        }

        let bound_ledger = env.ledger().sequence();
        let store = env.storage().persistent();
        let epoch: u32 = store.get(&DataKey::Epoch).unwrap_or(0);

        let att = RiskAttestation {
            root_hash: root_hash.clone(),
            total_liabilities: total_liabilities.clone(),
            reserves: reserves.clone(),
            max_conc_bps,
            min_coll_bps,
            reserve_holder: config.reserve_holder.clone(),
            reserve_token: config.reserve_token.clone(),
            bound_reserves: onchain_reserves,
            bound_ledger,
            timestamp: env.ledger().timestamp(),
            epoch,
        };
        store.set(&DataKey::RiskLatest, &att);
        // FIX 4 (M2): mirror the certified-solvent root into Latest so
        // `verify_inclusion` binds to THIS attestation's root, not a stale one.
        store.set(
            &DataKey::Latest,
            &Attestation {
                root_hash: root_hash.clone(),
                total_liabilities,
                reserves,
                reserve_holder: config.reserve_holder.clone(),
                reserve_token: config.reserve_token.clone(),
                bound_reserves: onchain_reserves,
                bound_ledger,
                timestamp: env.ledger().timestamp(),
                epoch,
                control_proven: true,
                non_omission_in_circuit: false,
            },
        );
        mark_root_seen(&env, &root_hash);
        store.set(&DataKey::Epoch, &(epoch + 1));

        env.events().publish(
            (symbol_short!("ledger"), symbol_short!("risk")),
            (epoch, root_hash, max_conc_bps, min_coll_bps),
        );
        epoch
    }

    /// The latest risk-limited attestation, if any (UPGRADE 3).
    pub fn get_risk_attestation(env: Env) -> Option<RiskAttestation> {
        env.storage().persistent().get(&DataKey::RiskLatest)
    }

    // ===== UPGRADE 2: MULTI-ASSET / MULTI-HOLDER RESERVES =====

    /// Configure the reserve legs the issuer backs liabilities with — one or more
    /// (holder, token) accounts aggregated together. Requires the primary
    /// (constructor-bound) reserve holder to authorize, so the aggregation target
    /// cannot be rigged by a non-controlling caller.
    ///
    /// FIX 2 (multi-asset inflation): the scale MUST be 1:1 (`scale_num ==
    /// scale_den`). Earlier the issuer could set an arbitrary `scale_num/scale_den`
    /// price and inflate a worthless token's contribution; that is an issuer-set
    /// price, not a fact about chain state, so it is rejected. This entrypoint now
    /// supports MULTI-HOLDER, SAME-UNIT aggregation only: every leg's token must be
    /// denominated in the same unit as the declared reserves (e.g. several USDC
    /// accounts). Cross-asset backing needs a real price oracle (see docs / NOT-YET).
    pub fn set_reserve_legs(env: Env, legs: Vec<ReserveLeg>) {
        if legs.is_empty() {
            panic_with_error!(&env, Error::NoReserveLegs);
        }
        let config: ReserveConfig = match env.storage().instance().get(&DataKey::Config) {
            Some(c) => c,
            None => panic_with_error!(&env, Error::NotConfigured),
        };
        for leg in legs.iter() {
            // Same-unit only: reject any non-1:1 (issuer-set price) scale.
            if leg.scale_num <= 0 || leg.scale_den <= 0 || leg.scale_num != leg.scale_den {
                panic_with_error!(&env, Error::BadReserveLeg);
            }
            // Same-unit also means SAME TOKEN as the constructor-bound reserve
            // denomination. Otherwise an issuer can mint a worthless SAC and
            // count it 1:1 as reserves.
            if leg.token != config.reserve_token {
                panic_with_error!(&env, Error::BadReserveToken);
            }
        }
        config.reserve_holder.require_auth();
        env.storage().persistent().set(&DataKey::ReserveLegs, &legs);
        env.events().publish(
            (symbol_short!("treasury"), symbol_short!("legs_set")),
            legs.len(),
        );
    }

    /// The configured reserve legs, if any (UPGRADE 2).
    pub fn reserve_legs(env: Env) -> Option<Vec<ReserveLeg>> {
        env.storage().persistent().get(&DataKey::ReserveLegs)
    }

    /// Sum the LIVE on-chain balances of every reserve leg, right now,
    /// cross-contract: `Σ balance(holder_i, token_i)` (all legs are same-unit,
    /// FIX 2). This is the real aggregate backing the multi-holder reserve.
    /// Overflow is an explicit error, never a silent saturating fallback (FIX 5).
    pub fn aggregate_reserves(env: Env) -> i128 {
        let legs: Vec<ReserveLeg> = match env.storage().persistent().get(&DataKey::ReserveLegs) {
            Some(l) => l,
            None => panic_with_error!(&env, Error::NoReserveLegs),
        };
        let mut total: i128 = 0;
        for leg in legs.iter() {
            // Same-unit (1:1) contribution: the live balance itself. `set_reserve_legs`
            // rejects any non-1:1 scale, so no issuer-set price is applied here.
            let bal = token::TokenClient::new(&env, &leg.token).balance(&leg.holder);
            total = match total.checked_add(bal) {
                Some(v) => v,
                None => panic_with_error!(&env, Error::ReserveOverflow),
            };
        }
        total
    }

    /// Verify a solvency Groth16 proof on-chain and bind its reserves figure to
    /// the AGGREGATE of multiple reserve legs (UPGRADE 2). Stores a
    /// `MultiAttestation` only if:
    ///   1. the Groth16 solvency proof verifies,
    ///   2. `reserves >= totalLiabilities`,
    ///   3. EVERY leg holder authorizes this call (`require_auth` per holder) —
    ///      control of ALL reserve accounts is proven, not just one, and
    ///   4. `reserves <= Σ scaled live balances` across every leg.
    ///
    /// So the single ZK-declared reserves figure is backed by real, live balances
    /// summed across multiple controlled accounts/assets. `public_signals` =
    /// [rootHash, totalLiabilities, reserves] (the base solvency circuit).
    pub fn submit_multi_attestation(
        env: Env,
        proof: BytesN<256>,
        public_signals: Vec<BytesN<32>>,
    ) -> u32 {
        if public_signals.len() != SOLVENCY_N_PUBLIC {
            panic_with_error!(&env, Error::MalformedPublicInputs);
        }
        assert_canonical_signals(&env, &public_signals);

        let vk = solvency_vk(&env);
        let parsed = Groth16Proof::from_bytes(&env, &proof);
        let fr = to_fr_vec(&env, &public_signals);
        if let Err(e) = verify(&env, &vk, &parsed, &fr) {
            panic_with_error!(&env, map_g16(e));
        }

        let root_hash = public_signals.get_unchecked(0);
        let total_liabilities = public_signals.get_unchecked(1);
        let reserves = public_signals.get_unchecked(2);

        reject_seen_root(&env, &root_hash);
        reject_weak_downgrade(&env);

        if !ge_be(&reserves, &total_liabilities) {
            panic_with_error!(&env, Error::Insolvent);
        }

        let legs: Vec<ReserveLeg> = match env.storage().persistent().get(&DataKey::ReserveLegs) {
            Some(l) => l,
            None => panic_with_error!(&env, Error::NoReserveLegs),
        };

        let declared_reserves = match be32_to_i128(&reserves) {
            Some(v) => v,
            None => panic_with_error!(&env, Error::ReservesOutOfRange),
        };

        // CONTROL of every leg + aggregate the live SAME-UNIT balances (FIX 2:
        // no issuer-set price). Overflow is an explicit error (FIX 5).
        let mut aggregate: i128 = 0;
        for leg in legs.iter() {
            // Each leg holder must authorize: control of ALL reserve accounts.
            leg.holder.require_auth();
            let bal = token::TokenClient::new(&env, &leg.token).balance(&leg.holder);
            aggregate = match aggregate.checked_add(bal) {
                Some(v) => v,
                None => panic_with_error!(&env, Error::ReserveOverflow),
            };
        }

        if declared_reserves > aggregate {
            panic_with_error!(&env, Error::ReserveUnbacked);
        }

        let bound_ledger = env.ledger().sequence();
        let store = env.storage().persistent();
        let epoch: u32 = store.get(&DataKey::Epoch).unwrap_or(0);

        let att = MultiAttestation {
            root_hash: root_hash.clone(),
            total_liabilities: total_liabilities.clone(),
            reserves: reserves.clone(),
            aggregate_reserves: aggregate,
            leg_count: legs.len(),
            bound_ledger,
            timestamp: env.ledger().timestamp(),
            epoch,
        };
        store.set(&DataKey::MultiLatest, &att);
        // FIX 4 (M2): mirror the certified-solvent root into Latest so
        // `verify_inclusion` binds to THIS attestation's root.
        {
            let first = legs.get_unchecked(0);
            store.set(
                &DataKey::Latest,
                &Attestation {
                    root_hash: root_hash.clone(),
                    total_liabilities,
                    reserves,
                    reserve_holder: first.holder.clone(),
                    reserve_token: first.token.clone(),
                    bound_reserves: aggregate,
                    bound_ledger,
                    timestamp: env.ledger().timestamp(),
                    epoch,
                    control_proven: true,
                    non_omission_in_circuit: false,
                },
            );
        }
        mark_root_seen(&env, &root_hash);
        store.set(&DataKey::Epoch, &(epoch + 1));

env.events().publish(
            (symbol_short!("ledger"), symbol_short!("multi")),
            (epoch, root_hash, aggregate),
        );
        epoch
    }

    /// The latest multi-asset/multi-holder attestation, if any (UPGRADE 2).
    pub fn get_multi_attestation(env: Env) -> Option<MultiAttestation> {
        env.storage().persistent().get(&DataKey::MultiLatest)
    }
}

fn reject_seen_root(env: &Env, root_hash: &BytesN<32>) {
    if env
        .storage()
        .persistent()
        .get::<_, bool>(&DataKey::SeenRoot(root_hash.clone()))
        .unwrap_or(false)
    {
        panic_with_error!(env, Error::RootAlreadyAttested);
    }
}

fn mark_root_seen(env: &Env, root_hash: &BytesN<32>) {
    env.storage()
        .persistent()
        .set(&DataKey::SeenRoot(root_hash.clone()), &true);
}

fn reject_weak_downgrade(env: &Env) {
    if let Some(latest) = env
        .storage()
        .persistent()
        .get::<_, Attestation>(&DataKey::Latest)
    {
        if latest.non_omission_in_circuit {
            panic_with_error!(env, Error::WeakAttestationDowngrade);
        }
    }
}

/// Rebuild the canonical bytes a user signs for one liability leaf. MUST match
/// the JS signer (`scripts/gen_signed_demo.js`) byte-for-byte:
///   LEAF_DOMAIN(16) || epoch(4 BE) || balance(16 BE i128) || nonce(8 BE) || leaf_commitment(32)
fn leaf_message(env: &Env, epoch: u32, leaf: &SignedLeaf) -> Bytes {
    let mut msg = Bytes::new(env);
    msg.extend_from_array(&LEAF_DOMAIN);
    msg.extend_from_array(&epoch.to_be_bytes());
    msg.extend_from_array(&leaf.balance.to_be_bytes());
    msg.extend_from_array(&leaf.nonce.to_be_bytes());
    msg.extend_from_array(&leaf.leaf_commitment.to_array());
    msg
}

#[cfg(test)]
mod test;
