//! On-chain verification tests driven by our REAL snarkjs Groth16 proofs.
//!
//! Fixtures in `test_fixtures.rs` are generated by
//! `contracts/scripts/convert.js` from `build/proofs/*.json` and are the exact
//! bytes submitted on testnet.

use super::*;
use soroban_sdk::{
    testutils::{Address as _, Ledger},
    token::StellarAssetClient,
    vec, Address, BytesN, Env, Vec,
};

mod fx {
    include!("test_fixtures.rs");
}

mod sfx {
    include!("signed_fixtures.rs");
}

mod ifx {
    include!("signed_incircuit_fixtures.rs");
}

mod rfx {
    include!("risk_fixtures.rs");
}

mod ufx {
    include!("unified_fixtures.rs");
}

/// Reserves carried in the in-circuit signed_solvency fixture (public signal 2).
const SIGNED_RESERVES: i128 = 30_000;
/// Reserves carried in the unified_solvency fixtures (public signal 2): 30000.
const UNIFIED_RESERVES: i128 = 30_000;
/// Reserves carried in the risk_solvency fixture (public signal 2): 118800.
const RISK_RESERVES: i128 = 118_800;

/// The reserves figure carried in the real solvency fixture: 0x0002e2d4.
const FIXTURE_RESERVES: i128 = 189_140;

fn public_vec(env: &Env, sigs: &[[u8; 32]]) -> Vec<BytesN<32>> {
    let mut v: Vec<BytesN<32>> = Vec::new(env);
    for s in sigs.iter() {
        v.push_back(BytesN::from_array(env, s));
    }
    v
}

/// Deploy a fresh reserve token (SAC) with `reserve_balance` minted to a new
/// holder, then deploy a TesseraLedger instance bound to that holder+token.
/// Returns the contract client plus the holder address so tests can inspect
/// the bound reserves.
fn setup(env: &Env, reserve_balance: i128) -> (TesseraLedgerClient<'_>, Address) {
    env.mock_all_auths();

    let sac_admin = Address::generate(env);
    let sac = env.register_stellar_asset_contract_v2(sac_admin);
    let token_address = sac.address();

    let reserve_holder = Address::generate(env);
    if reserve_balance > 0 {
        StellarAssetClient::new(env, &token_address).mint(&reserve_holder, &reserve_balance);
    }

    let id = env.register(
        TesseraLedger,
        (reserve_holder.clone(), token_address.clone()),
    );
    (TesseraLedgerClient::new(env, &id), reserve_holder)
}

/// Convenience: reserve holder fully backs the fixture reserves.
fn register(env: &Env) -> TesseraLedgerClient<'_> {
    setup(env, FIXTURE_RESERVES).0
}

#[test]
fn valid_solvency_proof_is_verified_and_stored() {
    let env = Env::default();
    env.ledger().set_timestamp(1_700_000_000);
    let client = register(&env);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);

    let epoch = client.submit_attestation(&proof, &signals);
    assert_eq!(epoch, 0);

    let att = client.get_attestation().expect("attestation stored");
    assert_eq!(att.root_hash, BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[0]));
    assert_eq!(att.total_liabilities, BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[1]));
    assert_eq!(att.reserves, BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[2]));
    // Reserves bound to the real on-chain balance.
    assert_eq!(att.bound_reserves, FIXTURE_RESERVES);
    assert_eq!(att.timestamp, 1_700_000_000);
    assert_eq!(client.epoch_count(), 1);
}

/// Reserve holder is over-backed (more USDC than declared): still accepted, and
/// the stored `bound_reserves` reflects the real (larger) on-chain balance.
#[test]
fn over_backed_reserves_accepted_and_binds_real_balance() {
    let env = Env::default();
    env.ledger().set_timestamp(1_700_000_000);
    let (client, holder) = setup(&env, FIXTURE_RESERVES + 1_000_000);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_attestation(&proof, &signals);

    let att = client.get_attestation().expect("stored");
    // Declared reserves (189140) <= on-chain balance (1189140); bound to real.
    assert_eq!(att.bound_reserves, FIXTURE_RESERVES + 1_000_000);
    assert_eq!(att.reserve_holder, holder);

    let (info_holder, info_bound, _ledger) =
        client.bound_reserve_info().expect("bound info");
    assert_eq!(info_holder, holder);
    assert_eq!(info_bound, FIXTURE_RESERVES + 1_000_000);
    assert_eq!(client.live_reserve_balance(), FIXTURE_RESERVES + 1_000_000);
}

/// Reserve holder's real balance is BELOW the ZK-declared reserves: the proof
/// is valid but the reserves figure is unbacked, so submit is rejected on-chain
/// (`ReserveUnbacked`) and nothing is stored.
#[test]
#[should_panic(expected = "Error(Contract, #5)")]
fn over_declared_reserves_rejected_when_unbacked() {
    let env = Env::default();
    // Only 100000 on-chain, but the proof declares reserves = 189140.
    let (client, _holder) = setup(&env, 100_000);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);

    client.submit_attestation(&proof, &signals); // must panic ReserveUnbacked
}

/// Exactly-backed edge (balance == declared reserves) is accepted.
#[test]
fn exactly_backed_reserves_accepted() {
    let env = Env::default();
    let (client, _holder) = setup(&env, FIXTURE_RESERVES);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let epoch = client.submit_attestation(&proof, &signals);
    assert_eq!(epoch, 0);
    assert_eq!(
        client.get_attestation().unwrap().bound_reserves,
        FIXTURE_RESERVES
    );
}

#[test]
#[should_panic]
fn tampered_solvency_proof_is_rejected() {
    let env = Env::default();
    let client = register(&env);

    // Same public signals, but the proof's A point was swapped for C.
    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF_TAMPERED);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);

    client.submit_attestation(&proof, &signals); // must panic (InvalidSolvencyProof)
}

#[test]
#[should_panic]
fn wrong_public_signal_count_is_rejected() {
    let env = Env::default();
    let client = register(&env);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    // Only 2 signals instead of 3.
    let mut signals: Vec<BytesN<32>> = Vec::new(&env);
    signals.push_back(BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[0]));
    signals.push_back(BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[1]));

    client.submit_attestation(&proof, &signals);
}

#[test]
fn valid_inclusion_proof_against_stored_root_returns_true() {
    let env = Env::default();
    let client = register(&env);

    // First store the solvency attestation.
    let sol_proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let sol_signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_attestation(&sol_proof, &sol_signals);

    // Then verify inclusion. The inclusion proof's rootHash equals the stored
    // solvency rootHash (same Merkle-sum tree).
    let inc_proof = BytesN::from_array(&env, &fx::INCLUSION_PROOF);
    let inc_signals = public_vec(&env, &fx::INCLUSION_PUBLIC);

    assert!(client.verify_inclusion(&inc_proof, &inc_signals));
}

#[test]
fn inclusion_against_wrong_root_returns_false() {
    let env = Env::default();
    let client = register(&env);

    let sol_proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let sol_signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_attestation(&sol_proof, &sol_signals);

    // Flip the claimed rootHash so it no longer matches the stored root.
    let mut bad_root = fx::INCLUSION_PUBLIC[0];
    bad_root[31] ^= 0x01;
    let bad_signals = vec![
        &env,
        BytesN::from_array(&env, &bad_root),
        BytesN::from_array(&env, &fx::INCLUSION_PUBLIC[1]),
    ];
    let inc_proof = BytesN::from_array(&env, &fx::INCLUSION_PROOF);

    assert!(!client.verify_inclusion(&inc_proof, &bad_signals));
}

#[test]
#[should_panic]
fn inclusion_before_any_attestation_panics() {
    let env = Env::default();
    let client = register(&env);

    let inc_proof = BytesN::from_array(&env, &fx::INCLUSION_PROOF);
    let inc_signals = public_vec(&env, &fx::INCLUSION_PUBLIC);
    client.verify_inclusion(&inc_proof, &inc_signals);
}

// ===== UPGRADE 2: proof of assets CONTROL (require_auth) =====

/// A stored attestation records that the reserve holder authorized it: control
/// of the reserve account is proven, not assumed.
#[test]
fn control_is_proven_when_reserve_holder_authorizes() {
    let env = Env::default();
    let client = register(&env); // setup() calls env.mock_all_auths()

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_attestation(&proof, &signals);

    assert!(client.get_attestation().unwrap().control_proven);
}

/// An issuer that does NOT control the reserve account cannot back an
/// attestation: without the reserve holder's authorization, submit fails.
#[test]
#[should_panic]
fn submit_without_reserve_holder_auth_fails() {
    let env = Env::default();
    let client = register(&env);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);

    // Provide NO authorizations for this call: the reserve holder does not
    // authorize it, so `reserve_holder.require_auth()` must panic. `set_auths`
    // overrides the mock-all-auths from setup for this single invocation.
    client.set_auths(&[]).submit_attestation(&proof, &signals);
}

// ===== UPGRADE 1: proof-of-liabilities NON-OMISSION (signed leaves) =====

fn signed_leaf_at(env: &Env, i: usize, epoch0: bool) -> SignedLeaf {
    if epoch0 {
        SignedLeaf {
            pubkey: BytesN::from_array(env, &sfx::E0_PUBKEYS[i]),
            balance: sfx::E0_BALANCES[i],
            nonce: sfx::E0_NONCES[i],
            leaf_commitment: BytesN::from_array(env, &sfx::E0_LEAVES[i]),
            sig: BytesN::from_array(env, &sfx::E0_SIGS[i]),
        }
    } else {
        SignedLeaf {
            pubkey: BytesN::from_array(env, &sfx::E1_PUBKEYS[i]),
            balance: sfx::E1_BALANCES[i],
            nonce: sfx::E1_NONCES[i],
            leaf_commitment: BytesN::from_array(env, &sfx::E1_LEAVES[i]),
            sig: BytesN::from_array(env, &sfx::E1_SIGS[i]),
        }
    }
}

/// Deploy + store the demo (honest) solvency attestation, reserve fully backed.
fn setup_demo(env: &Env, omitted: bool) -> TesseraLedgerClient<'_> {
    let (client, _h) = setup(env, sfx::DEMO_RESERVES);
    let (proof, signals) = if omitted {
        (
            BytesN::from_array(env, &sfx::DEMO_OMITTED_PROOF),
            public_vec(env, &sfx::DEMO_OMITTED_PUBLIC),
        )
    } else {
        (
            BytesN::from_array(env, &sfx::DEMO_SOLVENCY_PROOF),
            public_vec(env, &sfx::DEMO_SOLVENCY_PUBLIC),
        )
    };
    client.submit_attestation(&proof, &signals);
    client
}

/// Honest book: all four user-signed leaves register (each ed25519 sig verified
/// on-chain), the omitted-candidate user C is registered, and C's real inclusion
/// proof verifies against the attested Merkle-sum root.
#[test]
fn honest_signed_leaves_register_and_user_verifies_inclusion() {
    let env = Env::default();
    let client = setup_demo(&env, false);

    let mut leaves: Vec<SignedLeaf> = Vec::new(&env);
    for i in 0..4 {
        leaves.push_back(signed_leaf_at(&env, i, true));
    }
    let count = client.register_signed_leaves(&leaves);
    assert_eq!(count, 4);

    let c_leaf = BytesN::from_array(&env, &sfx::E0_LEAVES[sfx::DEMO_C_INDEX]);
    assert!(client.is_registered(&c_leaf), "user C must be registered");

    let inc_proof = BytesN::from_array(&env, &sfx::DEMO_INCLUSION_PROOF);
    let inc_signals = public_vec(&env, &sfx::DEMO_INCLUSION_PUBLIC);
    assert!(
        client.verify_inclusion(&inc_proof, &inc_signals),
        "user C inclusion must verify against the attested root"
    );

    let reg = client.signed_leaf_registry().unwrap();
    assert_eq!(reg.count, 4);
    assert_eq!(reg.epoch, 0);
}

/// Omitting issuer: builds a tree WITHOUT user C, registers only A, B, D. User C
/// is provably omitted — `is_registered` is false and C's inclusion proof does
/// not verify against the omitted root — yet C's ed25519-signed claim still
/// verifies ON-CHAIN, which is the cryptographic omission evidence.
#[test]
fn omitted_account_is_provably_absent_but_claim_still_verifies() {
    let env = Env::default();
    let client = setup_demo(&env, true); // omitted-tree attestation stored

    // Issuer registers only A, B, D (indices 0,1,3), dropping C (index 2).
    let mut leaves: Vec<SignedLeaf> = Vec::new(&env);
    for i in [0usize, 1, 3] {
        leaves.push_back(signed_leaf_at(&env, i, true));
    }
    assert_eq!(client.register_signed_leaves(&leaves), 3);

    // C is absent from the on-chain registry.
    let c_leaf = BytesN::from_array(&env, &sfx::E0_LEAVES[sfx::DEMO_C_INDEX]);
    assert!(!client.is_registered(&c_leaf), "user C must be absent");

    // C cannot prove inclusion against the omitted attested root.
    let inc_proof = BytesN::from_array(&env, &sfx::DEMO_INCLUSION_PROOF);
    let inc_signals = public_vec(&env, &sfx::DEMO_INCLUSION_PUBLIC);
    assert!(
        !client.verify_inclusion(&inc_proof, &inc_signals),
        "C inclusion must fail against the omitted root"
    );

    // But C's signed claim verifies on-chain: the issuer omitted a real account.
    let c = signed_leaf_at(&env, sfx::DEMO_C_INDEX, true);
    let bound = client.verify_signed_claim(&0u32, &c);
    assert_eq!(bound, c_leaf, "C's signature is bound to C's leaf commitment");
}

/// The issuer cannot fabricate a leaf: registering a set containing a forged
/// (tampered) signature panics during on-chain ed25519 verification, so nothing
/// is stored.
#[test]
#[should_panic]
fn forged_signed_leaf_is_rejected_on_chain() {
    let env = Env::default();
    let client = setup_demo(&env, false);

    let mut leaves: Vec<SignedLeaf> = Vec::new(&env);
    leaves.push_back(signed_leaf_at(&env, 0, true)); // genuine A
    // Forged C: correct pubkey/balance/leaf but a tampered signature.
    leaves.push_back(SignedLeaf {
        pubkey: BytesN::from_array(&env, &sfx::E0_PUBKEYS[sfx::DEMO_C_INDEX]),
        balance: sfx::E0_BALANCES[sfx::DEMO_C_INDEX],
        nonce: sfx::E0_NONCES[sfx::DEMO_C_INDEX],
        leaf_commitment: BytesN::from_array(&env, &sfx::E0_LEAVES[sfx::DEMO_C_INDEX]),
        sig: BytesN::from_array(&env, &sfx::FORGED_SIG),
    });
    client.register_signed_leaves(&leaves); // must panic
}

// ===== UPGRADE 1 (STRONGEST FORM): IN-CIRCUIT EdDSA non-omission =====
// ===== FIX 1: customer-self-registered keys, pinned on-chain =====

/// Every customer self-registers their Baby-JubJub key (== the honest proof's
/// public signer keys) under a distinct authorizing address.
fn register_all_keys(env: &Env, client: &TesseraLedgerClient) {
    for i in 0..4usize {
        let customer = Address::generate(env);
        client.register_customer_key(
            &customer,
            &BytesN::from_array(env, &ifx::REGISTERED_AX[i]),
            &BytesN::from_array(env, &ifx::REGISTERED_AY[i]),
        );
    }
}

/// Honest path: the four customers self-register their keys, then a signed_solvency
/// proof — whose SNARK verified every customer's Baby-JubJub EdDSA signature and
/// whose PUBLIC signer keys equal the registered list — verifies on-chain and stores
/// an attestation flagged `non_omission_in_circuit = true`. Completeness of
/// liabilities is enforced by the proof plus the on-chain key pin, not user vigilance.
#[test]
fn in_circuit_signed_solvency_verifies_and_flags_non_omission() {
    let env = Env::default();
    env.ledger().set_timestamp(1_700_000_000);
    let (client, _h) = setup(&env, SIGNED_RESERVES);

    register_all_keys(&env, &client);
    assert_eq!(client.registered_key_count(), 4);
    // Any customer can confirm their key is in the on-chain list.
    assert!(client.is_registered_key(
        &BytesN::from_array(&env, &ifx::REGISTERED_AX[2]),
        &BytesN::from_array(&env, &ifx::REGISTERED_AY[2]),
    ));

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    let epoch = client.submit_signed_attestation(&proof, &signals);
    assert_eq!(epoch, 0);

    let att = client.get_attestation().expect("stored");
    assert!(att.non_omission_in_circuit, "in-circuit non-omission must be flagged");
    assert!(att.control_proven);
    assert_eq!(att.bound_reserves, SIGNED_RESERVES);
    assert_eq!(att.root_hash, BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PUBLIC[0]));
    // Freshness counter advanced to the circuit epoch (0).
    assert_eq!(client.signed_epoch(), Some(0));
}

/// OMISSION rejected on-chain: the four customers are registered, then the issuer
/// submits a VALID proof that dropped registered customer C and substituted its own
/// filler key in slot C. The proof verifies (all four in-circuit signatures check),
/// but its public slot-C key does not match the registered C key, so the contract's
/// key pin rejects it with `RegisteredSetMismatch` (#10). The issuer cannot omit a
/// registered customer.
#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn in_circuit_omission_is_rejected_on_chain() {
    let env = Env::default();
    let (client, _h) = setup(&env, SIGNED_RESERVES);
    register_all_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_OMITTED_PROOF);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_OMITTED_PUBLIC);
    client.submit_signed_attestation(&proof, &signals); // must panic #10
}

/// Submitting before the full customer key list is self-registered is rejected
/// (`RegisteredSetNotSet`, #11): the completeness pin must exist first.
#[test]
#[should_panic(expected = "Error(Contract, #11)")]
fn in_circuit_signed_solvency_without_registered_keys_panics() {
    let env = Env::default();
    let (client, _h) = setup(&env, SIGNED_RESERVES);

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    client.submit_signed_attestation(&proof, &signals); // must panic #11
}

/// A tampered in-circuit proof (A point swapped for C) fails the on-chain pairing
/// check, so nothing is stored even though the keys are registered.
#[test]
#[should_panic]
fn in_circuit_signed_solvency_tampered_proof_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, SIGNED_RESERVES);
    register_all_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF_TAMPERED);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    client.submit_signed_attestation(&proof, &signals); // must panic (InvalidSolvencyProof)
}

/// FIX 4 freshness: replaying the SAME signed proof/root after it was accepted
/// is rejected before storage. The root-replay guard fires even before the
/// circuit-epoch check, so stale roots cannot be re-shown as fresh liabilities.
#[test]
#[should_panic(expected = "Error(Contract, #17)")]
fn in_circuit_stale_epoch_replay_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, SIGNED_RESERVES);
    register_all_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    client.submit_signed_attestation(&proof, &signals); // epoch 0 accepted
    client.submit_signed_attestation(&proof, &signals); // replay epoch 0 -> #14
}

// ===== UPGRADE 3: CONCENTRATION / RISK LIMITS =====

/// A healthy, diversified, over-collateralized book verifies on-chain and stores
/// a RiskAttestation recording the concentration cap (40%) and min collateral
/// ratio (105%) the proof satisfied. The whale-free / well-collateralized nature
/// is proven in the circuit, not asserted.
#[test]
fn risk_limited_book_verifies_and_records_limits() {
    let env = Env::default();
    env.ledger().set_timestamp(1_700_000_000);
    let (client, _h) = setup(&env, RISK_RESERVES);

    let proof = BytesN::from_array(&env, &rfx::RISK_SOLVENCY_PROOF);
    let signals = public_vec(&env, &rfx::RISK_SOLVENCY_PUBLIC);
    let epoch = client.submit_risk_attestation(&proof, &signals);
    assert_eq!(epoch, 0);

    let att = client.get_risk_attestation().expect("risk attestation stored");
    assert_eq!(att.max_conc_bps, 4000, "concentration cap = 40%");
    assert_eq!(att.min_coll_bps, 10500, "min collateralization = 105%");
    assert_eq!(att.bound_reserves, RISK_RESERVES);
    assert_eq!(att.root_hash, BytesN::from_array(&env, &rfx::RISK_SOLVENCY_PUBLIC[0]));
}

/// A tampered risk proof fails the on-chain pairing check; nothing is stored.
/// (The concentration/collateral BREACH negatives are proven at the circuit
/// level in scripts/prove_risk.sh: a book that breaches either limit is
/// UNPROVABLE, so no on-chain proof can exist to reject.)
#[test]
#[should_panic]
fn risk_tampered_proof_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, RISK_RESERVES);

    let proof = BytesN::from_array(&env, &rfx::RISK_SOLVENCY_PROOF_TAMPERED);
    let signals = public_vec(&env, &rfx::RISK_SOLVENCY_PUBLIC);
    client.submit_risk_attestation(&proof, &signals); // must panic
}

// ===== UNIFIED CIRCUIT: health + non-omission + risk in one proof (#57) =====

/// Every customer self-registers their unified-circuit Baby-JubJub key (== the
/// honest unified proof's public signer keys) under a distinct address.
fn register_unified_keys(env: &Env, client: &TesseraLedgerClient) {
    for i in 0..4usize {
        let customer = Address::generate(env);
        client.register_customer_key(
            &customer,
            &BytesN::from_array(env, &ufx::UNIFIED_REGISTERED_AX[i]),
            &BytesN::from_array(env, &ufx::UNIFIED_REGISTERED_AY[i]),
        );
    }
}

/// Honest path: one on-chain proof certifies health (non-negative, correct sum,
/// total <= reserves), non-omission (4 real in-circuit signatures pinned to the
/// self-registered keys), AND risk bounds (40% conc / 105% coll). Stores with
/// `non_omission_in_circuit = true` and advances the unified freshness counter.
#[test]
fn unified_honest_book_verifies_and_flags_all_properties() {
    let env = Env::default();
    env.ledger().set_timestamp(1_700_000_000);
    let (client, _h) = setup(&env, UNIFIED_RESERVES);

    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    assert_eq!(signals.len(), 14);
    let epoch = client.submit_unified_attestation(&proof, &signals);
    assert_eq!(epoch, 0);

    let att = client.get_attestation().expect("stored");
    assert!(att.non_omission_in_circuit, "unified proof is non-omitting");
    assert!(att.control_proven);
    assert_eq!(att.bound_reserves, UNIFIED_RESERVES);
    assert_eq!(att.root_hash, BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC[0]));
    assert_eq!(att.total_liabilities, BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC[1]));
    assert_eq!(client.unified_epoch(), Some(0));
    assert_eq!(client.epoch_count(), 1);
}

/// OMISSION rejected: valid unified proof, but slot-2 public key is the
/// issuer's filler — the FIX-1 pin fires `RegisteredSetMismatch` (#10).
#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn unified_omission_is_rejected_on_chain() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_OMITTED_PROOF);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_OMITTED_PUBLIC);
    client.submit_unified_attestation(&proof, &signals); // must panic #10
}

/// No registered key list yet: rejected (`RegisteredSetNotSet`, #11).
#[test]
#[should_panic(expected = "Error(Contract, #11)")]
fn unified_without_registered_keys_panics() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    client.submit_unified_attestation(&proof, &signals); // must panic #11
}

/// Tampered unified proof fails the pairing check; nothing is stored.
#[test]
#[should_panic]
fn unified_tampered_proof_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF_TAMPERED);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    client.submit_unified_attestation(&proof, &signals); // must panic
}

/// STALE epoch rejected (#14): after the epoch-1 book is accepted, the honest
/// epoch-0 book (different root so the seen-root guard passes, same keys so
/// the key pin passes) fails the unified freshness check.
#[test]
#[should_panic(expected = "Error(Contract, #14)")]
fn unified_stale_epoch_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let e1_proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_E1_PROOF);
    let e1_signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_E1_PUBLIC);
    client.submit_unified_attestation(&e1_proof, &e1_signals); // epoch 1 accepted
    assert_eq!(client.unified_epoch(), Some(1));

    let e0_proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let e0_signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    client.submit_unified_attestation(&e0_proof, &e0_signals); // stale -> #14
}

/// Same unified root replayed: the seen-root guard fires (#17) even though the
/// proof itself is valid.
#[test]
#[should_panic(expected = "Error(Contract, #17)")]
fn unified_same_root_replay_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    client.submit_unified_attestation(&proof, &signals);
    client.submit_unified_attestation(&proof, &signals); // replay -> #17
}

/// Valid unified proof but declared reserves (30000) exceed the real balance:
/// rejected (`ReserveUnbacked`, #5), nothing stored.
#[test]
#[should_panic(expected = "Error(Contract, #5)")]
fn unified_unbacked_reserves_are_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, 1_000);
    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    client.submit_unified_attestation(&proof, &signals); // must panic #5
}

/// Wrong signal count (13 instead of 14): rejected (`MalformedPublicInputs`, #2).
#[test]
#[should_panic(expected = "Error(Contract, #2)")]
fn unified_wrong_signal_count_is_rejected() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let mut signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    signals.pop_back();
    client.submit_unified_attestation(&proof, &signals); // must panic #2
}

/// Freshness ADVANCE (companion to the stale/replay negatives): submitting the
/// epoch-1 book after epoch-0 succeeds and moves the unified counter to 1.
#[test]
fn unified_epoch_advance_accepts_greater() {
    let env = Env::default();
    let (client, _h) = setup(&env, UNIFIED_RESERVES);
    register_unified_keys(&env, &client);

    let e0_proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_PROOF);
    let e0_signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_PUBLIC);
    assert_eq!(client.submit_unified_attestation(&e0_proof, &e0_signals), 0);
    assert_eq!(client.unified_epoch(), Some(0));

    let e1_proof = BytesN::from_array(&env, &ufx::UNIFIED_SOLVENCY_E1_PROOF);
    let e1_signals = public_vec(&env, &ufx::UNIFIED_SOLVENCY_E1_PUBLIC);
    assert_eq!(client.submit_unified_attestation(&e1_proof, &e1_signals), 1);
    assert_eq!(client.unified_epoch(), Some(1));
    assert_eq!(client.epoch_count(), 2);
}

/// LIVE FINDING #61 (testnet 2026-09-10): after a signed (non-omission)
/// Latest is stored, a risk submit is rejected with `WeakAttestationDowngrade`
/// (#20) — the contract never lets a weaker root overwrite a stronger bound
/// root, even though the risk proof itself is valid and backed. Sequencing
/// consequence: submit risk BEFORE signed if both are wanted on one instance.
#[test]
#[should_panic(expected = "Error(Contract, #20)")]
fn risk_after_signed_latest_is_rejected_as_downgrade() {
    let env = Env::default();
    // Covers both fixtures: signed declares 30000, risk declares 118800.
    let (client, _h) = setup(&env, RISK_RESERVES);
    register_all_keys(&env, &client);

    let proof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF);
    let signals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    client.submit_signed_attestation(&proof, &signals); // stronger Latest stored

    let rproof = BytesN::from_array(&env, &rfx::RISK_SOLVENCY_PROOF);
    let rsignals = public_vec(&env, &rfx::RISK_SOLVENCY_PUBLIC);
    client.submit_risk_attestation(&rproof, &rsignals); // must panic #20
}

// ===== PRICED RESERVES: oracle-scaled legs (#64) =====

/// On-chain mock oracle implementing the EXACT method the generated
/// `OracleClient` calls (`get_price(feed_id) -> Option<(price, ledger)>`).
/// Scripted per test via set/clear_quote. Production uses a Reflector
/// adapter with the identical method shape (NOT wired here).
#[contracttype]
enum MockKey {
    Quote(u32),
}

#[contract]
struct MockOracle;

#[contractimpl]
impl MockOracle {
    pub fn set_quote(env: Env, feed_id: u32, price: i128, ledger: u32) {
        env.storage()
            .persistent()
            .set(&MockKey::Quote(feed_id), &(price, ledger));
    }
    pub fn clear_quote(env: Env, feed_id: u32) {
        env.storage().persistent().remove(&MockKey::Quote(feed_id));
    }
    pub fn get_price(env: Env, feed_id: u32) -> Option<(i128, u32)> {
        env.storage().persistent().get(&MockKey::Quote(feed_id))
    }
}

/// Deploy token + mint leg balances, register the mock oracle, deploy
/// TesseraLedger, and pin oracle config (reflector=mock, staleness=100,
/// feeds=[1,2]). Quotes are scripted per test against ledger 0 unless the
/// test bumps the sequence.
fn setup_priced(
    env: &Env,
    bal_a: i128,
    bal_b: i128,
) -> (
    TesseraLedgerClient<'_>,
    MockOracleClient<'_>,
    Address,
    Address,
    Address,
) {
    env.mock_all_auths();

    let sac_admin = Address::generate(env);
    let sac = env.register_stellar_asset_contract_v2(sac_admin);
    let token = sac.address();
    let holder_a = Address::generate(env);
    let holder_b = Address::generate(env);
    StellarAssetClient::new(env, &token).mint(&holder_a, &bal_a);
    StellarAssetClient::new(env, &token).mint(&holder_b, &bal_b);

    let mock_id = env.register(MockOracle, ());
    let mock = MockOracleClient::new(env, &mock_id);

    let gov = Address::generate(env);
    let id = env.register(TesseraLedger, (gov.clone(), token.clone()));
    // Fund the constructor holder too: cross-path tests (signed/risk submits
    // in a priced env, #72) need its balance to back their fixtures.
    StellarAssetClient::new(env, &token).mint(&gov, &300_000);
    let client = TesseraLedgerClient::new(env, &id);
    client.set_oracle_config(&mock_id, &100, &vec![env, 1u32, 2u32]);

    (client, mock, token, holder_a, holder_b)
}

/// Build the two standard priced legs for holders with pre-minted balances.
fn priced_legs(
    env: &Env,
    holder_a: &Address,
    holder_b: &Address,
    token: &Address,
) -> Vec<PricedLeg> {
    vec![
        env,
        PricedLeg { holder: holder_a.clone(), token: token.clone(), feed_id: 1 },
        PricedLeg { holder: holder_b.clone(), token: token.clone(), feed_id: 2 },
    ]
}

/// Gate hand-computed fixture: 100000 @ 1.0 + 1000000 @ 0.1234567 =
/// 100000 + 123456 (truncated) = 223456 — MUST match the JS trial
/// (`scripts/oracle_math.test.js`) exactly, on-chain.
#[test]
fn priced_hand_aggregate_matches_trial() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0); // USDC @ 1.0, fresh
    mock.set_quote(&2, &1_234_567, &0); // XLM @ 0.1234567, fresh

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    let epoch = client.submit_priced_attestation(&proof, &signals, &legs);
    assert_eq!(epoch, 0);

    let att = client.get_priced_attestation().expect("priced attestation stored");
    assert_eq!(att.aggregate_reserves, 223_456);
    assert_eq!(att.leg_count, 2);
    assert_eq!(att.oldest_price_ledger, 0);
    // Mirrors into Latest for inclusion binding, like the multi path.
    let latest = client.get_attestation().expect("Latest mirrored");
    assert_eq!(latest.bound_reserves, 223_456);
    assert_eq!(latest.root_hash, BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[0]));
}

/// Stale quote on the second leg (age 101 > 100): `StalePrice` (#23), even
/// though the first leg is fresh — one stale leg aborts the whole submit.
#[test]
#[should_panic(expected = "Error(Contract, #23)")]
fn priced_stale_quote_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    env.ledger().set_sequence_number(101);
    mock.set_quote(&1, &10_000_000, &101); // fresh at current ledger
    mock.set_quote(&2, &1_234_567, &0); // age 101 -> stale

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #23
}

/// No quote for a pinned feed: `MissingPrice` (#25) — never a default price.
#[test]
#[should_panic(expected = "Error(Contract, #25)")]
fn priced_missing_quote_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.clear_quote(&2); // feed 2 pinned but quoteless

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #25
}

/// Negative quote: `BadPrice` (#24).
#[test]
#[should_panic(expected = "Error(Contract, #24)")]
fn priced_negative_quote_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &-1_000_000, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #24
}

/// Zero quote: `BadPrice` (#24) — a zero price would zero the backing.
#[test]
#[should_panic(expected = "Error(Contract, #24)")]
fn priced_zero_price_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &0, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #24
}

/// Leg references a feed ID never pinned at config time: `UnknownPriceFeed`
/// (#26) — even with a quote present for it on the oracle.
#[test]
#[should_panic(expected = "Error(Contract, #26)")]
fn priced_unknown_feed_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&9, &10_000_000, &0); // quoted but never pinned

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let mut legs = priced_legs(&env, &holder_a, &holder_b, &token);
    legs.set(
        1,
        PricedLeg { holder: holder_b.clone(), token: token.clone(), feed_id: 9 },
    );
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #26
}

/// `balance * price` overflowing i128: explicit `ReserveOverflow` (#15),
/// never a saturating fallback (FIX 5 parity).
#[test]
#[should_panic(expected = "Error(Contract, #15)")]
fn priced_overflow_is_explicit() {
    let env = Env::default();
    let huge = 10i128.pow(30);
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, huge, 0);

    mock.set_quote(&1, &10i128.pow(31), &0); // 1e30 * 1e31 = 1e61 overflows
    mock.set_quote(&2, &10_000_000, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #15
}

/// No authorizations at all: the first leg holder's `require_auth` panics.
/// Per-holder control is load-bearing on the priced path too.
#[test]
#[should_panic]
fn priced_without_holder_auth_fails() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &1_234_567, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client
        .set_auths(&[])
        .submit_priced_attestation(&proof, &signals, &legs); // must panic
}

/// Priced path without oracle config: `OracleNotConfigured` (#27).
#[test]
#[should_panic(expected = "Error(Contract, #27)")]
fn priced_without_oracle_config_panics() {
    let env = Env::default();
    // Base setup only: token + funded holder + ledger, NO oracle wiring.
    let (client, holder) = setup(&env, FIXTURE_RESERVES);
    let token = client.reserve_config().expect("config").reserve_token;

    let legs = vec![
        &env,
        PricedLeg { holder: holder.clone(), token: token.clone(), feed_id: 1 },
    ];
    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #27
}

/// Empty leg set: `NoReserveLegs` (#12) — a priced attestation over nothing.
#[test]
#[should_panic(expected = "Error(Contract, #12)")]
fn priced_empty_legs_panics() {
    let env = Env::default();
    let (client, _mock, _token, _a, _b) = setup_priced(&env, 100_000, 1_000_000);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    client.submit_priced_attestation(&proof, &signals, &vec![&env]); // must panic #12
}

/// Empty feed list at config time: `UnknownPriceFeed` (#26) — fail closed at
/// config, not at first submit.
#[test]
#[should_panic(expected = "Error(Contract, #26)")]
fn oracle_config_empty_feeds_panics() {
    let env = Env::default();
    let (client, _mock, token, _a, _b) = setup_priced(&env, 100_000, 1_000_000);

    client.set_oracle_config(&token, &100, &vec![&env]); // must panic #26
}

/// Backed proof, unbacked aggregate (100 << 189140 declared): `ReserveUnbacked`
/// (#5) — the oracle-scaled floor binds like the live-balance floor.
#[test]
#[should_panic(expected = "Error(Contract, #5)")]
fn priced_unbacked_aggregate_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 50, 50);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &10_000_000, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #5
}

/// Same priced root replayed: the seen-root guard fires (#17).
#[test]
#[should_panic(expected = "Error(Contract, #17)")]
fn priced_same_root_replay_is_rejected() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &1_234_567, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs);
    client.submit_priced_attestation(&proof, &signals, &legs); // replay -> #17
}

/// Priced submit after a signed Latest: `WeakAttestationDowngrade` (#20).
/// Extends the live #61 finding (risk path) to the priced path — no weaker
/// root overwrites a stronger one, whichever weak path tries.
#[test]
#[should_panic(expected = "Error(Contract, #20)")]
fn priced_after_signed_latest_is_rejected_as_downgrade() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);
    register_all_keys(&env, &client);

    let sproof = BytesN::from_array(&env, &ifx::SIGNED_SOLVENCY_PROOF);
    let ssignals = public_vec(&env, &ifx::SIGNED_SOLVENCY_PUBLIC);
    client.submit_signed_attestation(&sproof, &ssignals); // stronger Latest stored

    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &1_234_567, &0);
    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // must panic #20
}

/// Staleness BOUNDARY: age exactly 100 (== max) still passes on-chain —
/// parity with the JS trial (`1100 - 1000` passes, `1101` rejects).
#[test]
fn priced_staleness_boundary_100_passes() {
    let env = Env::default();
    let (client, mock, token, holder_a, holder_b) = setup_priced(&env, 100_000, 1_000_000);

    env.ledger().set_sequence_number(100);
    mock.set_quote(&1, &10_000_000, &0);
    mock.set_quote(&2, &1_234_567, &0);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    let legs = priced_legs(&env, &holder_a, &holder_b, &token);
    client.submit_priced_attestation(&proof, &signals, &legs); // age 100 OK

    let att = client.get_priced_attestation().expect("stored");
    assert_eq!(att.aggregate_reserves, 223_456);
}

/// Oracle config without holder auth: the primary holder must authorize, so a
/// non-controlling caller cannot rig the price source.
#[test]
#[should_panic]
fn oracle_config_without_holder_auth_fails() {
    let env = Env::default();
    let (client, _mock, token, _a, _b) = setup_priced(&env, 100_000, 1_000_000);

    client
        .set_auths(&[])
        .set_oracle_config(&token, &100, &vec![&env, 1u32]); // must panic
}

/// Non-canonical public signal (the field modulus itself, `>= r`): rejected
/// (`NonCanonicalSignal`, #16) BEFORE any pairing work — the M3 aliasing bar.
#[test]
#[should_panic(expected = "Error(Contract, #16)")]
fn non_canonical_signal_is_rejected() {
    let env = Env::default();
    let client = register(&env);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let mut signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    signals.set(0, BytesN::from_array(&env, &BN254_FR_MODULUS));
    client.submit_attestation(&proof, &signals); // must panic #16
}

// ===== UPGRADE 2: MULTI-ASSET / MULTI-HOLDER RESERVES =====

/// Mint `amount` of a fresh SAC to `holder`; return the token address.
fn new_token(env: &Env, holder: &Address, amount: i128) -> Address {
    let sac = env.register_stellar_asset_contract_v2(Address::generate(env));
    let addr = sac.address();
    StellarAssetClient::new(env, &addr).mint(holder, &amount);
    addr
}

/// The single ZK-declared reserves figure (189140) is backed by the AGGREGATE of
/// TWO SAME-TOKEN reserve legs across TWO holders. This closes the arbitrary-token
/// inflation bug: multi-reserve means multi-holder same-token, not issuer-priced
/// multi-asset.
#[test]
fn multi_holder_same_token_reserves_aggregate_across_holders() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_700_000_000);

    let sac_admin = Address::generate(&env);
    let base_sac = env.register_stellar_asset_contract_v2(sac_admin);
    let reserve_token = base_sac.address();
    let gov = Address::generate(&env);
    let id = env.register(TesseraLedger, (gov.clone(), reserve_token.clone()));
    let client = TesseraLedgerClient::new(&env, &id);

    let holder_a = Address::generate(&env);
    let holder_b = Address::generate(&env);
    StellarAssetClient::new(&env, &reserve_token).mint(&holder_a, &100_000);
    StellarAssetClient::new(&env, &reserve_token).mint(&holder_b, &100_000);

    let legs = vec![
        &env,
        ReserveLeg { holder: holder_a.clone(), token: reserve_token.clone(), scale_num: 1, scale_den: 1 },
        ReserveLeg { holder: holder_b.clone(), token: reserve_token.clone(), scale_num: 1, scale_den: 1 },
    ];
    client.set_reserve_legs(&legs);

    assert_eq!(client.aggregate_reserves(), 200_000);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC); // reserves = 189140
    let epoch = client.submit_multi_attestation(&proof, &signals);
    assert_eq!(epoch, 0);

    let att = client.get_multi_attestation().expect("multi attestation stored");
    assert_eq!(att.leg_count, 2);
    assert_eq!(att.aggregate_reserves, 200_000);
    assert_eq!(att.reserves, BytesN::from_array(&env, &fx::SOLVENCY_PUBLIC[2]));
}

/// If the summed same-token balances fall BELOW the declared reserves, the multi
/// attestation is rejected (`ReserveUnbacked`, #5): the aggregate does not cover
/// the ZK-declared reserves.
#[test]
#[should_panic(expected = "Error(Contract, #5)")]
fn multi_holder_same_token_reserves_rejected_when_aggregate_below_declared() {
    let env = Env::default();
    env.mock_all_auths();

    let sac_admin = Address::generate(&env);
    let base_sac = env.register_stellar_asset_contract_v2(sac_admin);
    let reserve_token = base_sac.address();
    let gov = Address::generate(&env);
    let id = env.register(TesseraLedger, (gov.clone(), reserve_token.clone()));
    let client = TesseraLedgerClient::new(&env, &id);

    let holder_a = Address::generate(&env);
    StellarAssetClient::new(&env, &reserve_token).mint(&holder_a, &100_000); // only 100000 < 189140
    let legs = vec![
        &env,
        ReserveLeg { holder: holder_a, token: reserve_token, scale_num: 1, scale_den: 1 },
    ];
    client.set_reserve_legs(&legs);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC); // reserves = 189140
    client.submit_multi_attestation(&proof, &signals); // must panic #5
}

/// Control of ALL legs is required: if any leg holder does not authorize, the
/// multi attestation fails (`require_auth` per holder).
#[test]
#[should_panic]
fn multi_asset_reserves_require_control_of_every_leg() {
    let env = Env::default();
    env.mock_all_auths();

    let sac_admin = Address::generate(&env);
    let base_sac = env.register_stellar_asset_contract_v2(sac_admin);
    let gov = Address::generate(&env);
    let id = env.register(TesseraLedger, (gov.clone(), base_sac.address()));
    let client = TesseraLedgerClient::new(&env, &id);

    let holder_a = Address::generate(&env);
    let holder_b = Address::generate(&env);
    let token_a = new_token(&env, &holder_a, 150_000);
    let token_b = new_token(&env, &holder_b, 150_000);
    let legs = vec![
        &env,
        ReserveLeg { holder: holder_a.clone(), token: token_a, scale_num: 1, scale_den: 1 },
        ReserveLeg { holder: holder_b.clone(), token: token_b, scale_num: 1, scale_den: 1 },
    ];
    client.set_reserve_legs(&legs);

    let proof = BytesN::from_array(&env, &fx::SOLVENCY_PROOF);
    let signals = public_vec(&env, &fx::SOLVENCY_PUBLIC);
    // Authorize ONLY holder_a (and the token reads); holder_b does not authorize.
    client
        .set_auths(&[])
        .submit_multi_attestation(&proof, &signals); // must panic at holder_b.require_auth
}

/// FIX 2: a non-1:1 scale (an issuer-set price) is rejected by `set_reserve_legs`
/// with `BadReserveLeg` (#13). Only same-unit aggregation is allowed; an issuer
/// cannot mint a worthless token and scale it up to fake backing.

/// FIX 2b: even 1:1 reserve legs must use the constructor-bound reserve token.
/// A worthless arbitrary SAC cannot be counted at face value as reserves.
#[test]
#[should_panic(expected = "Error(Contract, #22)")]
fn arbitrary_token_reserve_leg_is_rejected() {
    let env = Env::default();
    env.mock_all_auths();

    let sac_admin = Address::generate(&env);
    let base_sac = env.register_stellar_asset_contract_v2(sac_admin);
    let gov = Address::generate(&env);
    let id = env.register(TesseraLedger, (gov.clone(), base_sac.address()));
    let client = TesseraLedgerClient::new(&env, &id);

    let holder = Address::generate(&env);
    let fake_token = new_token(&env, &holder, 1_000_000);
    let legs = vec![
        &env,
        ReserveLeg { holder, token: fake_token, scale_num: 1, scale_den: 1 },
    ];
    client.set_reserve_legs(&legs); // must panic #22
}

#[test]
#[should_panic(expected = "Error(Contract, #13)")]
fn non_unit_scale_reserve_leg_is_rejected() {
    let env = Env::default();
    env.mock_all_auths();

    let sac_admin = Address::generate(&env);
    let base_sac = env.register_stellar_asset_contract_v2(sac_admin);
    let gov = Address::generate(&env);
    let id = env.register(TesseraLedger, (gov.clone(), base_sac.address()));
    let client = TesseraLedgerClient::new(&env, &id);

    let holder = Address::generate(&env);
    let token = new_token(&env, &holder, 100_000);
    let legs = vec![
        &env,
        ReserveLeg { holder, token, scale_num: 2, scale_den: 1 }, // issuer-set price
    ];
    client.set_reserve_legs(&legs); // must panic #13
}
