// ---------------------------------------------------------------------------
// gen_signed_fixtures.js  --  Turn the UPGRADE-1 demo proofs + ed25519 signed
// leaves into (a) Rust unit-test fixtures and (b) ready-to-invoke Soroban CLI
// argument JSON for the testnet demonstration.
//
// Reads:
//   build/proofs/demo_{solvency,solvency_omitted,inclusion}_{proof,public}.json
//   contracts/artifacts/signed-demo.json   (from gen_signed_demo.js)
// Writes:
//   contracts/tessera-ledger/src/signed_fixtures.rs
//   contracts/artifacts/signed-onchain-args.json
// ---------------------------------------------------------------------------

const fs = require("fs");
const path = require("path");

const PROJECT = path.resolve(__dirname, "..");
const SRC = path.join(PROJECT, "contracts/tessera-ledger/src");
const ART = path.join(PROJECT, "contracts/artifacts");
const P = path.join(PROJECT, "build/proofs");

// ---- field/point encoders (identical layout to contracts/scripts/convert.js) ----
function feBytes(dec) {
  let v = BigInt(dec);
  if (v < 0n) throw new Error("negative fe");
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
  if (v !== 0n) throw new Error("fe > 32 bytes");
  return out;
}
const concat = (arrs) => {
  const n = arrs.reduce((s, a) => s + a.length, 0);
  const o = new Uint8Array(n); let k = 0;
  for (const a of arrs) { o.set(a, k); k += a.length; }
  return o;
};
const g1 = (p) => concat([feBytes(p[0]), feBytes(p[1])]);
const g2 = (p) => concat([feBytes(p[0][1]), feBytes(p[0][0]), feBytes(p[1][1]), feBytes(p[1][0])]);
const proofBytes = (pr) => concat([g1(pr.pi_a), g2(pr.pi_b), g1(pr.pi_c)]);
const rustBytes = (b) => "[" + Array.from(b).map((x) => "0x" + x.toString(16).padStart(2, "0")).join(", ") + "]";
const hex = (b) => Buffer.from(b).toString("hex");

const load = (f) => JSON.parse(fs.readFileSync(path.join(P, f)));

const solProof = proofBytes(load("demo_solvency_proof.json"));
const solPub = load("demo_solvency_public.json");
const omProof = proofBytes(load("demo_solvency_omitted_proof.json"));
const omPub = load("demo_solvency_omitted_public.json");
const incProof = proofBytes(load("demo_inclusion_proof.json"));
const incPub = load("demo_inclusion_public.json");

const demo = JSON.parse(fs.readFileSync(path.join(ART, "signed-demo.json")));

// ---- Rust fixtures --------------------------------------------------------
function pubArr(name, pub) {
  let s = `pub const ${name}: [[u8; 32]; ${pub.length}] = [\n`;
  for (const sig of pub) s += `    ${rustBytes(feBytes(sig))},\n`;
  return s + "];\n";
}
function leafSet(name, leaves) {
  const n = leaves.length;
  const bytes32 = (h) => rustBytes(Buffer.from(h, "hex"));
  const bytes64 = (h) => rustBytes(Buffer.from(h, "hex"));
  let s = "";
  s += `pub const ${name}_PUBKEYS: [[u8; 32]; ${n}] = [\n` + leaves.map((l) => `    ${bytes32(l.pubkey_hex)},\n`).join("") + "];\n";
  s += `pub const ${name}_BALANCES: [i128; ${n}] = [${leaves.map((l) => l.balance).join(", ")}];\n`;
  s += `pub const ${name}_NONCES: [u64; ${n}] = [${leaves.map((l) => l.nonce).join(", ")}];\n`;
  s += `pub const ${name}_LEAVES: [[u8; 32]; ${n}] = [\n` + leaves.map((l) => `    ${bytes32(l.leaf_commitment_hex)},\n`).join("") + "];\n";
  s += `pub const ${name}_SIGS: [[u8; 64]; ${n}] = [\n` + leaves.map((l) => `    ${bytes64(l.sig_hex)},\n`).join("") + "];\n";
  return s;
}

let rs = "";
rs += "// Auto-generated by scripts/gen_signed_fixtures.js. Do NOT edit by hand.\n";
rs += "// UPGRADE-1 demo: pubkey-bound Merkle-sum tree, real ed25519 signed leaves,\n";
rs += "// honest vs. account-omitted variants. All proofs are real BN254 Groth16.\n\n";
rs += `pub const DEMO_RESERVES: i128 = ${demo.honest.reserves};\n`;
rs += `pub const DEMO_C_INDEX: usize = 2; // user C is the omitted account\n\n`;
rs += `pub const DEMO_SOLVENCY_PROOF: [u8; 256] = ${rustBytes(solProof)};\n`;
rs += pubArr("DEMO_SOLVENCY_PUBLIC", solPub) + "\n";
rs += `pub const DEMO_OMITTED_PROOF: [u8; 256] = ${rustBytes(omProof)};\n`;
rs += pubArr("DEMO_OMITTED_PUBLIC", omPub) + "\n";
rs += `pub const DEMO_INCLUSION_PROOF: [u8; 256] = ${rustBytes(incProof)};\n`;
rs += pubArr("DEMO_INCLUSION_PUBLIC", incPub) + "\n";
rs += "// Epoch-0 signed leaves (honest registration: A, B, C, D).\n";
rs += leafSet("E0", demo.epoch0_signed_leaves) + "\n";
rs += "// Epoch-1 signed leaves (same users re-sign for epoch 1; the omission demo\n";
rs += "// registers only A, B, D and drops C, whose epoch-1 claim still verifies).\n";
rs += leafSet("E1", demo.epoch1_signed_leaves) + "\n";
rs += "// A forged leaf: user C's epoch-0 leaf with one signature byte flipped.\n";
rs += `pub const FORGED_SIG: [u8; 64] = ${rustBytes(Buffer.from(demo.forged_leaf.sig_hex, "hex"))};\n`;
fs.writeFileSync(path.join(SRC, "signed_fixtures.rs"), rs);

// ---- Soroban CLI argument JSON -------------------------------------------
const leafCli = (l) => ({
  pubkey: l.pubkey_hex,
  balance: l.balance,
  nonce: Number(l.nonce),
  leaf_commitment: l.leaf_commitment_hex,
  sig: l.sig_hex,
});
const forgedCli = leafCli(demo.forged_leaf);
forgedCli.sig = demo.forged_leaf.sig_hex;

const args = {
  note: "UPGRADE-1 signed-leaf testnet args. Proofs are real BN254 Groth16; leaves carry real ed25519 signatures verified on-chain.",
  honest_solvency: { proof_hex: hex(solProof), public_hex: solPub.map((s) => hex(feBytes(s))), public_dec: solPub },
  omitted_solvency: { proof_hex: hex(omProof), public_hex: omPub.map((s) => hex(feBytes(s))), public_dec: omPub },
  user_c_inclusion: { proof_hex: hex(incProof), public_hex: incPub.map((s) => hex(feBytes(s))), public_dec: incPub },
  epoch0_leaves_cli: demo.epoch0_signed_leaves.map(leafCli),
  epoch1_leaves_no_c_cli: demo.epoch1_signed_leaves.filter((l) => l.name !== "C").map(leafCli),
  user_c_epoch1_claim_cli: leafCli(demo.epoch1_signed_leaves.find((l) => l.name === "C")),
  forged_leaf_cli: forgedCli,
};
fs.writeFileSync(path.join(ART, "signed-onchain-args.json"), JSON.stringify(args, null, 2));

console.log("wrote src/signed_fixtures.rs and artifacts/signed-onchain-args.json");
console.log("demo reserves:", demo.honest.reserves, "| honest total:", demo.honest.totalLiabilities, "| omitted total:", demo.omitted.totalLiabilities);
